### ISSUE TITLE
[Feature Request] show number, book name, and author in series view

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#10]
Similar view like ABS to show number, book name and author in the series view. 
![image](https://github.com/rasmuslos/ShelfPlayer/assets/4202657/ad8b204b-a1ab-4313-8d64-e5f0577242ef)

**Comment by rasmuslos** [comment]
Apple Books does not show the title and author and I think that's reasonable as they are always on the cover. But I think, that the "status bar" at the bottom could use an overhaul, including showing the series number

**Comment by gh0sti** [comment]
> Apple Books does not show the title and author and I think that's reasonable as they are always on the cover. But I think, that the "status bar" at the bottom could use an overhaul, including showing the series number

That would be awesome and understandable.

**Comment by rasmuslos** [comment]
I ended up removing the bottom bar, but I added an series sort option
