### ISSUE TITLE
[Feature Request] Playback above 2x

### ISSUE THREAD

**Issue by genebean** [rasmuslos/ShelfPlayer#104]
My partner enjoys fast playback on some books... any chance you'd implement speeds faster than 2x?

**Comment by rasmuslos** [comment]
You can set a custom playback speed option in the account sheet. It can go up to 4x

**Comment by MadMud** [comment]
> You can set a custom playback speed option in the account sheet. It can go up to 4x

Thanks! 
For the next soul looking: go to

Search -> top right: person symbol

Just because it took me an embarrassingly long time to find the account sheet 😅
