### ISSUE TITLE
[Feature Request] Dialogue for playback speed

### ISSUE THREAD

**Issue by genebean** [rasmuslos/ShelfPlayer#105]
I think it'd be nice to have a dialogue to pick playback speed from instead of just tapping through them.

**Comment by zhimiaoli** [comment]
long press the playback rate number to show the selector, and you can add one customized playback  rate in settings.

**Comment by genebean** [comment]
Very cool, thanks!

**Comment by zhimiaoli** [comment]
you can close issue #104 and this issue  if there are no further questions.
