### ISSUE TITLE
Unable to sign in with sso

### ISSUE THREAD

**Issue by muppie** [rasmuslos/ShelfPlayer#106]
Hi,
I’m trying to login to audiobookshelf but my user identity is managed by Authentik but it doesn’t work. I get server not foubd when accessing the FQDN and user not found when using the IP address directly. It works as expected in the web ui and the native ios app. 

latest version of everything. 

Any thoughts?

**Comment by rasmuslos** [comment]
Can you describe your setup and the unexpected behavior in more detail?

**Comment by rasmuslos** [comment]
I will close this due to inactivity. Feel free to comment on this again and I will reopen this issue.

**Comment by pavelzw** [comment]
@rasmuslos I have the same issues.

I configured OIDC for audiobookshelf using the following guide: https://www.audiobookshelf.org/guides/oidc_authentication

This requires an authentik setup to be present, see https://docs.goauthentik.io/docs/installation/docker-compose

On audiobookshelf's side, it's configured as follows:
<img width="968" alt="image" src="https://github.com/user-attachments/assets/bbce7713-6638-45ff-980c-c5c46ce1ca15">

Using the Web-UI, everything works as expected: i'm redirected to my authentik instance, log in there and get redirected back to audiobookshelf and can sign in from there.
Using [plappa](https://apps.apple.com/de/app/plappa/id6475201956) (alternative to this project), it works as well.

When entering the Server-URL in ShelfPlayer and clicking on "Next", it says "Login failed".

Is this enough information to reopen the issue?

**Comment by cat24max** [comment]
@rasmuslos I have the exact same issue. OIDC login seems to be broken in ShelfPlayer.

**Comment by rasmuslos** [comment]
I forgot to respond but you forgot to add the `shelfplayer://callback` URL to the allow list. It says you should do so when you are promoted to select a authentication method and the callback is missing in the screenshot.

**Comment by cat24max** [comment]
> I forgot to respond but you forgot to add the `shelfplayer://callback` URL to the allow list. It says you should do so when you are promoted to select a authentication method and the callback is missing in the screenshot.

Thanks, I actually figured that out in the exact moment you replied.

For anyone else trying this: You have to add `shelfplayer://callback` (or `plappa://oauth`) in ABS.
Also, in your OIDC server, you have to add another redirect URL: `https://abs.domain/auth/openid/callback` AND `https://abs.domain/auth/openid/mobile-redirect`

**Comment by pavelzw** [comment]
Thanks, that works for me as well :)
