### ISSUE TITLE
[Feature Request]Sleep timer reset/snooze mode.

### ISSUE THREAD

**Issue by tehguitarist** [rasmuslos/ShelfPlayer#113]
Would it be possible to have a toggle, that has the sleep timer reset (after audio stops) to the selected time?

Use case would be quite often I’ll put on an audiobook before sleeping, but sometimes the sleep timer will run out before I actually go to sleep. It would be nice to just have to hit play again on my headphones/home screen rather than open the app and reset the timer.

Not a big or important thing, just thought I’d throw it out there.

**Comment by zosologist** [comment]
Came here to request this and was delighted to see someone else in need as well

**Comment by rasmuslos** [comment]
Im currently restructuring some things, but when I am done I will add this feature.

**Comment by rasmuslos** [comment]
You can now press play during a ten-second window after the timer expires, which will cause the sleep timer to extend by its previous setting.
