### ISSUE TITLE
[Bug] Bookmark "time" property should be an integer

### ISSUE THREAD

**Issue by thedualspace** [rasmuslos/ShelfPlayer#115]
The time property on bookmarks should be an integer according to the [ABS docs](https://api.audiobookshelf.org/#audio-bookmark), ShelfPlayer is saving as a float.

This is causing an issue with other ABS clients, in my case Plappa.

More details here: 
https://github.com/LeoKlaus/plappa/issues/137

**Comment by rasmuslos** [comment]
Fixed 👍
