### ISSUE TITLE
Audiobookshelf server not found

### ISSUE THREAD

**Issue by weswitt** [rasmuslos/ShelfPlayer#116]
I just bought the iOS app and installed it only to find that it will not connect to my server. I was previously using the beta version that worked perfectly. I'm getting the error: "Audiobookshelf server not found".  And yes I'm using the right URL. I can access the server from the browser on the same iPhone. 

What do I need to do to get this working??

**Comment by rasmuslos** [comment]
What kind of environment are you running both apps in? Can you describe your network setup in detail?

**Comment by rasmuslos** [comment]
Is the traffic routed through the internet or your local network?

**Comment by rasmuslos** [comment]
What beta version were you using before?

**Comment by weswitt** [comment]
I have no idea

**Comment by rasmuslos** [comment]
Check if ABS and ShelfPlayer are up to date, your firewall and URL (protocol, port, ... [should be something like https://your.domain without a trailing `/`])

**Comment by ketan-vijayvargiya** [comment]
Running into this problem as well.

**Comment by rasmuslos** [comment]
@weswitt Are you using the latest version of ABS and ShelfPlayer and do you have any additional security measures, such as an WAF in place?

**Comment by ketan-vijayvargiya** [comment]
I too was running into a similar-ish issue where ShelfPlayer just threw a "Login failed" and refused to even connect even though my instance's URL was correct.

I use OIDC on ABS and I found out the solution was to change the _Allowed Mobile Redirect URIs_ field on my ABS instance from the default value, which was `audiobookshelf://oauth`, to `*`. Works now.

Not sure if @weswitt is facing the same problem.

**Comment by Crisco** [comment]
I was having issues connecting initially as well and spent some time searching for documentation on the Mobile Redirect URI for OIDC until I looked at the debug logs and found `shelfplayer://callback`. Once that was added I was able to login. I prefer using explicit allowed URIs vs just using a wildcard, but if all you care about is getting it to work initially, either should suffice.

**Comment by lvermehren** [comment]
Do I need OIDC for Shelfplayer to work? Because I also can't connect to my domain via Shelfplayer

**Comment by rasmuslos** [comment]
No, make sure you don't include a trailing slash

**Comment by codebox** [comment]
I know this issue is closed but adding this note for anyone who has the same problem as me. I host an ABS server on my local network and was getting the 'Audiobookshelf server not found' error. Turns out iOS has a special permission to allow apps to access the local network (search for 'local network' in settings and you will find it) - it was turned off for ShelfPlayer, as soon as I turned it on everything started working.

**Comment by benjick** [comment]
I have the same issue. Accessing via browser works. Clicking "connect" takes me to an almost empty view

![Image](https://github.com/user-attachments/assets/408b8b72-af97-4db0-962e-7c9481436375)

![Image](https://github.com/user-attachments/assets/6bb9c109-3bd7-4ae3-99aa-5400c1e1b924)

**Comment by rasmuslos** [comment]
@benjick This is the wrong repository. https://github.com/advplyr/audiobookshelf-app/issues is the correct one.

**Comment by benjick** [comment]
@rasmuslos sorry 🤦‍♂️ I was googling and reading lots of issues and this felt like the closest one (except it being the wrong repo 😅)
