### ISSUE TITLE
[Feature Request] Improved session handling

### ISSUE THREAD

**Issue by justcallmelarry** [rasmuslos/ShelfPlayer#119]
So I've been using the app on and off for a while, and I love the improvements that are coming all the time!

Would love to see some improvements to the session handling though, like the following:
- [x] End current listening session after X minutes of inactivity (maybe 10 would be a good round number)
- [x] Send ended sessions once there is connection, similar to how sessions are sent for completed books when possible in the current functionality

This would solve a few issues for me (at least):
- [ ] I jump back and forth between listening on my computer and on my phone, this means that I do not always mark the book as finished while in the app, but rather on the computer.
- [ ] Semi-often i listen to 1-2h of a book before deciding to DNF it. This means that I currently do not get any listening sessions for those, since they are never marked as  finished.
- [x] This would also improve QoL since stats would be updated in real time, which is more of a nice to have than an actual issue.

I could see some issues with this, like increased complexity, though I would guess that most of the issues I can envision are already handled in the apps since you can probably listen to, and finish multiple books while being "offline", needing the app to take care of all of those sessions in either case.

It also seems like the app already stores multiple sessions per book, as longer books get the sessions spread out over several days when finished.

**Comment by rasmuslos** [comment]
This is related to https://github.com/rasmuslos/ShelfPlayer/issues/90 (https://github.com/advplyr/audiobookshelf/pull/2920#issuecomment-2109642192). I am currently updating a lot of ShelfPlayers components but improve the session handling when I am done

**Comment by rasmuslos** [comment]
I made some changes, here is the gist:

- ShelfPlayer will now monitor network changes and will initiate a synchronization if
  1. The ABS-Server is reachable
  2. There are cached changes that need to be synced
- Local progress entities are now updated every second while progress is still synced with the server every 30 seconds
- Playing a downloaded item will now create a new listening session, like streaming would, instead of just syncing offline progress entities
