### ISSUE TITLE
Crashing on username/password entry

### ISSUE THREAD

**Issue by PulsarFTW** [rasmuslos/ShelfPlayer#12]
Testing the side loaded version, the app opens and I can enter my server URL but when entering my username and password the app just completely crashes out. 

Apologies this is a very unspecific report, if you let me know any steps you want me to take to share more information I would be happy to.

**Comment by rasmuslos** [comment]
What tool are you using to sideload?

**Comment by rasmuslos** [comment]
This should fix your issue: https://github.com/rasmuslos/ShelfPlayer/releases/tag/v2.0.6

**Comment by PulsarFTW** [comment]
It works - Thanks!

Looking to test it out now whilst I wait to see how the App store release goes. I love the native ABS app, but this fits iOS theme very well.
