### ISSUE TITLE
Sporadically jumps to new point in book

### ISSUE THREAD

**Issue by dan-drews** [rasmuslos/ShelfPlayer#120]
Good morning,

I’ve been unable to consistently reproduce this bug, but I mainly listen in car play or when wearing headphones when running.

From time to time I’ll be listening to an audio book in my car, then run an errand and get back in my car, and the audiobook will jump to a completely different point in the story.

I do have the books downloaded into the app locally, so I wonder if that possibly causes problems with reporting the state of the book back to the server?

is there any logging or debugging steps I could perform to help narrow down this issue? Or any other info I can provide? Happy to help debug

**Comment by gh0sti** [comment]
are you saying it jumps backwards? There's a setting called smart rewind.

**Comment by dan-drews** [comment]
I think it usually jumps backwards, yes, but we are talking like 30 minutes to an hour backwards, to a different chapter. I'm assuming smart rewind is just jumping back a few seconds to refresh you based on where you left off, similar to what podcast apps do?

**Comment by dan-drews** [comment]
Okay yeah, I'm reading the code here, and it looks like smart rewind is used if you pause too long, it'll rewind 10 seconds if I'm understanding the code correctly

https://github.com/rasmuslos/ShelfPlayer/blob/d7d36aaa75cc89b3fc6ce110315e33c738bba628/ShelfPlayerKit/Sources/SPPlayback/AudioPlayer%2BSleepTimer.swift#L16

This is definitely jumping more than 10 seconds, or even 10 minutes, so that isn't the culprit

**Comment by rasmuslos** [comment]
Hey,

are you using the same device when you are running and when sitting in the car?

**Comment by dan-drews** [comment]
Yeah, always playing from my iphone. The last time it happened, my earbuds weren't involved either. I drove about 5 minutes to the store, made a quick stop inside for some groceries, came back out and played and noticed it jumped ahead.

I also noticed that there seemed to be an issue with the chapters. I knew that chapter 3 had just started, and then i noticed that it seemed to have jumped around, so I tried to manually start chapter 3, and it actually played chapter 4 instead (The narrator says the chapter name at the start of each chapter, and when I had chapter 3 selected, it said "Chapter 4"). Then, the next day, the files were aligned properly (Chapter 3 was actually chapter 3).

Not sure if this is helpful or not, is there any possibility that either audiobookshelf or shelfplayer has an off-by-one error happening in some instances when it comes to resuming?

**Comment by rasmuslos** [comment]
Can you try this in the official app or the web client? I would guess that you have an issue with the audio file.

**Comment by dan-drews** [comment]
The audio files are correct, as I said above, the chapters were properly aligned  the next day (And maybe would have been fine if i killed and restarted the app.

But in the web client, I just tried specifically playing chapter 3, and the narrator said "Chapter 3" at the start, so the issue is short-lived, and has only presented in ShelfPlayer.

**Comment by rasmuslos** [comment]
This is helpful, the issue seems to be with downloading files. Can you download them again to check if it was a one-of thing?

**Comment by dan-drews** [comment]
I have moved onto a new book, and this book is actually all one file in .m4b format (The previous one was individual mp3 files per chapter)

I've downloaded this book, and I'll report back if it jumps around, but since it's all one file, I expect it wont' be an issue with this one

**Comment by rasmuslos** [comment]
@dan-drews how did it go? Can I close the issue?

**Comment by dan-drews** [comment]
All the books i've listened to lately were single-file m4b formats and they worked perfectly. There might still be an outstanding issue with individual MP3 files, but i dont' have any books in that format i plan on reading coming up, so we can close this
