### ISSUE TITLE
[Feature Request] Automatically play next book in a series

### ISSUE THREAD

**Issue by kgraefe** [rasmuslos/ShelfPlayer#121]
I have a kids series with hundreds of short episodes (~15min). We mostly listen to them in the car where I cannot manually select a new episode every 15min. It would be very desirable if ShelfPlayer would automatically continue with the next episode if one is finished.

**Comment by rasmuslos** [comment]
A queue feature for podcasts and audiobooks is already in development

**Comment by Hutch79** [comment]
Would love to see this feature as well. Currently pretty annoying if I'm in the car or at the gym and the episode ends mid workout/drive 😅

**Comment by rasmuslos** [comment]
You have to enable this feature in the settings app, but its implemented now and awaiting release

**Comment by gh0sti** [comment]
> You have to enable this feature in the settings app, but its implemented now and awaiting release

Just downloaded 2.4.4 and I don't see this option in settings to enable download next in series.

**Comment by rasmuslos** [comment]
Yes, sorry for the confusion: 2.4.4 it’s just a bug fix to allow some users to authorise again. This is part of a bigger update 2.5.0, which is still in development. I rewrote a lot of stuff, including the audio player, but there are still some missing things, and it might sadly take a little bit more time before the next major update is ready…

**Comment by rasmuslos** [comment]
The 2.4.4 update is build from this branch https://github.com/rasmuslos/ShelfPlayer/tree/duration-fix which is based of 2.4.3 and only includes the bug fix
