### ISSUE TITLE
Missing Audiobook Files in iOS Version

### ISSUE THREAD

**Issue by reezelazar** [rasmuslos/ShelfPlayer#122]
Description:

While using the Shelfplayer app, I encountered an issue that affects the functionality and user experience. Below are the details of the error:

App: Shelfplayer
Version: 2.4.2 (297)
OS: iOS 17.5.1

Issue:
200 audiobook files have been collected in a series and are in sequence. They are all correctly shown in the desktop app of AudioBookShelf 2.11.0. However, the Shelfplayer app on iOS only displays 184 items.

Steps to Reproduce:

	1.	Open the Shelfplayer app on an iOS device running version 17.5.1.
	2.	Navigate to the series containing the 200 audiobook files.
	3.	Observe that only 184 items are displayed instead of the full 200.

Expected Result:
All 200 audiobook files should be displayed in sequence, matching the desktop app’s display.

Actual Result:
Only 184 audiobook files are displayed in the Shelfplayer app, with 16 files missing.

Additional Information:

	•	The missing files are displayed correctly in the AudioBookShelf desktop app (version 2.11.0).
	•	The issue persists after restarting the app and the device.
	•	No error messages are shown in the app.

Steps Taken to Troubleshoot:

	•	Restarted the Shelfplayer app.
	•	Rebooted the iOS device.
	•	Checked for any available updates for the Shelfplayer app and iOS.

**Comment by rasmuslos** [comment]
Are the books visible in the "Library" tab of the app?

**Comment by reezelazar** [comment]
Yes, all is there

**Comment by rasmuslos** [comment]
Can you check again with version 2.5.0?
