### ISSUE TITLE
Shelf Player Goes Offline After Closing - iPhone 13

### ISSUE THREAD

**Issue by Heisenberg9469** [rasmuslos/ShelfPlayer#125]
For the past few days, the Shelf Player app on my iPhone 13 has been going offline every time I close it. When I reopen the app, it won’t reconnect, and the only solution is to delete my account and log in again. I’ve already tried reinstalling the app, but the problem continues.

Please help with a fix!

Got IOS 17.5.1
Latest App Version
ABS 2.4.2

**Comment by gh0sti** [comment]
> For the past few days, the Shelf Player app on my iPhone 13 has been going offline every time I close it. When I reopen the app, it won’t reconnect, and the only solution is to delete my account and log in again. I’ve already tried reinstalling the app, but the problem continues.
> 
> Please help with a fix!
> 
> Got IOS 17.5.1 Latest App Version ABS 2.4.2

You are several versions behind on ABS. Changelog [v2.12.3](https://github.com/advplyr/audiobookshelf/releases/tag/v2.12.3) (08/09/2024)

**Comment by gh0sti** [comment]
some changes are coming to SP for offline mode in latest commit. https://github.com/rasmuslos/ShelfPlayer/commit/8def8b43d4600579557128f5d33f6454fb08deab

**Comment by Heisenberg9469** [comment]
Ähhm, I see on my pc 1.12.3. The app Shows me 2.4.2 (maybe App version?) 
But I noticed that the ABS apps on Android all have the same pattern, so it's probably not ShelfPlayer's fault. Sorry!
