### ISSUE TITLE
[Bug] Download issue, downloaded files are not recognized by the app

### ISSUE THREAD

**Issue by fxMem** [rasmuslos/ShelfPlayer#128]
I've encountered a strange thing with one book series,

1. I do a storage clean via system menu to make sure there's no leftovers
2. Login to server, etc
3. I create separate storage location for local files in the app interface 
4. I download the 1 first book of the series, and verify the file presence in the storage folder, its there along with cover file
5. I download the 2 book. Now in file system I see both books downloaded, 2 audio files and 2 cover files
6. In app interface app marks book 2 as downloaded, but suddenly doens't see download files for book 1 anymore (no green checkmark, button stream instead of play etc)
7. I download the book again, and it downloads into file system with (1) postfix, putting the file next to the old one. But now in app I see book 1 as downloaded again, and book 2 is losing info about downloaded file

**Comment by rasmuslos** [comment]
Did you manage to get it working?
