### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by dboggus** [rasmuslos/ShelfPlayer#129]
I have a little under 700 books in my library and while I can search from the Audiobookshelf web interface without issue, whenever I try to search from ShelfPlayer, the loading icon just spins for a very long time and no results show. 

I have found that searching for book or series names does not work but searching for Author names does work. 

Also, when I click on a series name from a book I get the same spinning loading icon with no results or I get a "Series unavailable" message.

I am using the latest version of ShelfPlayer from the iOS App Store and version 2.12.3 of Audiobookshelf

**Comment by gh0sti** [comment]
I can concur with this. ABS on iOS searches fine and returns results. SP loads forever when searching.

**Comment by rasmuslos** [comment]
There were some API breaking changes in ABS
