### ISSUE TITLE
App stops playing with screen off

### ISSUE THREAD

**Issue by ursuscamp** [rasmuslos/ShelfPlayer#130]
ShelfPlayer: 2.4.3
iOS: 17.5.1
ABS: 2.12.3

App stops playing when screen goes off. Not 100% of the time, it's sporadic. It happens as soon as the screen goes off, and picks back up again as soon as the screen comes back on. 

Still happens even if the book is downloaded.

**Comment by rasmuslos** [comment]
This it happen again?
