### ISSUE TITLE
Cant Play OGG/OPUS Files

### ISSUE THREAD

**Issue by R3iniX** [rasmuslos/ShelfPlayer#133]
I cant seem to play ogg/opus files, when I click listen nothing happens

ShelfPlayer: 2.4.3
iOS: 17.5.1
Audiobookshelf: 2.12.3

**Comment by gh0sti** [comment]
I don't believe those file formats are supported on iOS.

**Comment by jakob11git** [comment]
Hm I have other iOS apps that work fine with Opus, and it's also natively supported on macOS. Would be interesting to know something definitive about iOS Opus support.

**Comment by rasmuslos** [comment]
[I don't think iOS supports opus](https://stackoverflow.com/questions/1535836/video-file-formats-supported-in-iphone). Did you download the book or did you try to stream it?

**Comment by timtips** [comment]
I also tried to play opus files with shelfplayer without success. The behaviour is exactly as described by @R3iniX in both cases (downloaded and streamed). This is really limiting the usefulness of the app for me. Other iOS apps do play opus without a problem. I don't know how they do it (play:Sub) for example does play my navidrome opus files without issues.

**Comment by rasmuslos** [comment]
Is downloading opus audiobooks possible in other abs apps?

**Comment by rasmuslos** [comment]
It’s not possible in the official abs app and there seems to be no API on the server which could allow this…
