### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by gyrene2083** [rasmuslos/ShelfPlayer#134]
I just purchased the app, and entered my server, ie https://myserver.com (without out a forward slash at the end) and while it seems that I'm logged into my server the app is just showing a spinning circle with the word loading on it. 

I tried out plappa and it just connects with no issues. I don't have WAF or OpenID setup. I'm not sure what else I'm missing. Please advise.

**Comment by gh0sti** [comment]
You sure you are adding the correct url? 

Are you doing Nginix or just accessing by ip? 

You might need the port id added to the URL to sign in example http://192.168.1.x:1234/

If you have it on a specific port you will need to add it.

**Comment by gyrene2083** [comment]
I’m using the site I’m hosting gave me, I never setup nginx unless the host site has it and I don’t know about. I didn’t try to using the ip, I’ll try that and see what happens.

From: Gh0sti ***@***.***>
Date: Wednesday, September 4, 2024 at 14:22
To: rasmuslos/ShelfPlayer ***@***.***>
Cc: gyrene2083 ***@***.***>, Author ***@***.***>
Subject: Re: [rasmuslos/ShelfPlayer] Stuck on loading screen (Issue #134)

You sure you are adding the correct url?

Are you doing Nginix or just accessing by ip?

You might need the port id added to the URL to sign in example http://192.168.1.x:1234/

If you have it on a specific port you will need to add it.

**Comment by rasmuslos** [comment]
> I just purchased the app, and entered my server, ie https://myserver.com (without out a forward slash at the end) and while it seems that I'm logged into my server the app is just showing a spinning circle with the word loading on it.
> 
> I tried out plappa and it just connects with no issues. I don't have WAF or OpenID setup. I'm not sure what else I'm missing. Please advise.

Did you try to restart the app? Does the spinner appear in a sheet or is it just there when you launch the app?

**Comment by gyrene2083** [comment]
I did reboot the app and I rebooted the server as well. Below is what I am seeing on my phone.

[
![DEEB37CB-A576-4D3D-B4CE-F259D41A547D](https://github.com/user-attachments/assets/96a73999-827b-45af-9ee6-00c5c598be2f)
](url)

**Comment by rasmuslos** [comment]
Do the other tabs work?

**Comment by gyrene2083** [comment]
I can go through the other tabs but there's nothing there. I just tested logging in to my local server and it works with no problem. But If I try my cloud server, the above is what you see.

**Comment by rasmuslos** [comment]
That's really strange because then it's not an error with the underlying models. Is there anything special about your setup, that you can think of, that may be responsible?

**Comment by saalaataa** [comment]
@gyrene2083 if you're using ABS 2.13+ version, try to downgrade to 2.12.3. It seems from 2.13 there is a change in the login process. I was having access issue and after downgrade to v2.12.3 I can use shelfplayer back again. 

BTW. plappa released newer version that addressed this problem and its working with latest release of ABS.

**Comment by rasmuslos** [comment]
This is an entirely different issue, logging in works fine, as indicated by the fact they're actually able to view the main content. As far as I can tell plappa is responsible for breaking ShelfPlayer for you, I have already implemented a solution and am waiting for another user to verify that it is working.

BTW. i don't want to blame plappa until I confirmed that it is actually the cause of this problem, but it looks a lot like it is.

**Comment by saalaataa** [comment]
> It seems like your issue is caused by the latest plappa update, not ShelfPlayer or ABS. But it's not related to this issue at all, this user is able to login, but parsing library items fails for some reason.

well, plappa is working fine, web access is working good. Wheras, with shelfplayer is not able to log in until I downgrade to older version of ABS. What plappa has to do with it. I just suggested @gyrene2083 option to check, as this may be related, or at least he can check if it is ABS related.

**Comment by gyrene2083** [comment]
@saalaataa, thank you for the suggestion. I have 2.13.3 installed locally as well as in the cloud. Shelfplayer plays fine off my local server, but when I connect to my cloud installation I get the above screen. 

Plappa works fine on both local and cloud server installations.

**Comment by rasmuslos** [comment]
@gyrene2083 di you have any custom HTTP headers setup?

**Comment by gyrene2083** [comment]
I do not. I have no idea where to get them to input them on the app.

**Comment by rasmuslos** [comment]
Just to get this straight: you are able to log into your cloud instance (the sheet [the thing sliding up from the bottom] disappears and the "Welcome" message goes away), but you are unable to get any of the tabs (including the series one to load)?
Can you check if you can switch libraries (top right hand corner)?

**Comment by gyrene2083** [comment]
That is crazy! I clicked on the library as you said and it loaded. But initially logging into the app I get that screenshot I sent you. 

I just tested a few books and they stream perfectly, which is great, but I am still curious about the initial login.

**Comment by rasmuslos** [comment]
I think the problem is that you have multiple instances. ShelfPlayer remembers the last library you selected, and if the library (or rather a library going by the id XY) cannot be found (because it was part of a different instance) ShelfPlayer is unable to load items inside this library.

Great to hear that the issue has ben resolved.
If you are curious about the things @saalaataa and I were talking about see https://github.com/rasmuslos/ShelfPlayer/issues/136#issuecomment-2338923741
