### ISSUE TITLE
Search Broken again?

### ISSUE THREAD

**Issue by dboggus** [rasmuslos/ShelfPlayer#138]
Search appears to be broken again. I get the loading spinner with no results showing up. Maybe Audiobookshelf changed something in the API again. 

Running the latest version of the app from the App Store and version 2.13.4 of Audiobookshelf.

**Comment by gh0sti** [comment]
searching for authors works but searching for individual books doesn't work.

SP 2.4.4
ABS 2.13.4
iOS 18.1 b3

**Comment by rasmuslos** [comment]
I based the fix for #135 on `2.4.3` but for some reason the tag actual code was based of `2.4.2`, so the search fix in `2.4.3` was missing for some reason? I will release an update with both fixes today...
