### ISSUE TITLE
[Feature Request] Handle multiple series for a book

### ISSUE THREAD

**Issue by tehguitarist** [rasmuslos/ShelfPlayer#139]
Currently (And this may well have changed) only one series is displayed. It's unclear how this series is chosen (even ABS is unclear, it doesn't seem to be order of creation, or alphabetical, so perhaps UUID?)
It would be nice to see if a book has multiple series within the book description.

To be clear, the series show correctly, it's just the books not showing multiple series in the description, only one.

This has larger UI ramifications (other books in series display), so not anything important.

Use cases for multiple series in ABS is overall and sub series where collections are maybe innapropriate.

For example, I do use collections for Star Wars books given the scope and relative disconnectedness, but for Terry Pratchett's Discworld, there is is the main Discworld series, and then within that, separate storylines.

**Comment by rasmuslos** [comment]
Where would you like to see all series enumerated? The audiobook view already does it, the series name should consist of all of them and tapping it should bring up a menu where you can navigate to each one.
The context menus don't do that right now, but will in `2.5.0`.

Are there any other places I missed, I don't use multiple series personally, so I have to rely on feedback to find these.

**Comment by tehguitarist** [comment]
Maybe I’m going crazy but I’m seeing it all where I could have sworn that I wasn’t before. I’ll have a look around though. There are only two broad series I use it for as I’m not hugely thrilled by how ABS handles multiple series anyway.

**Comment by tehguitarist** [comment]
I think I may have found the issue, it seems like in the “Continue series” section, when opening the book multiple series aren’t showing, only one. Opening the book in other places seems to work though. It also doesn’t seem to be showing the series that is being continued.

for example, if it is book 3 in the sub-series, but book 10 in the main series, it displays twice (as expected), but only shows the sub-series on both instances of it.

**Comment by rasmuslos** [comment]
This is actually caused by ABS. The home API endpoint only sends the series you started, not all of them, when a book is in the "continue series row". But version 2.5.0 will fix this, when the view is loaded the audiobook is fetched and updated.

On a slightly related topic: Would you like to join the TestFlight for 2.5.0? You provided a lot of helpful feedback, and I would be delighted if you could send me an E-Mail to git@rfk.io from the address you use for iTunes so that I can add you!
