### ISSUE TITLE
Sort Order in CarPlay app

### ISSUE THREAD

**Issue by jessearmstrong** [rasmuslos/ShelfPlayer#141]
The CarPlay app is great! But there is one thing that I think is a big UX issue. 

I am not sure if the sort order is alphabetical or not, but if you have multiple books downloaded to ShelfPlayer I often have to use the arrow buttons and search for the book I am actively listening to. I think the sort order should be by date last played, only if I am starting a new book should I have to poke around looking for the title to play. Fixing this sort order would be huge for the usability of the CarPlay app. 

Thank you!

Having the native CarPlay app is one of my top reasons for using Shelfplayer over other apps (including audio bookshelf native)

**Comment by jessearmstrong** [comment]
@rasmuslos Is this something that you would consider to make the CarPlay app easier to use in the car?

**Comment by rasmuslos** [comment]
yes but you are not going to speed the implementation by asking me multiple times
