### ISSUE TITLE
Continue series tweaking 2.5 beta

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#144]
![image](https://github.com/user-attachments/assets/0c71e83b-7782-4806-91e7-10c520fc84af)

I think this view could use some tweaking for what's next. I actually don't know what it should look like. 

The other question I have is shouldn't SP download the next book to be ready to play or does it just stream the next book? I did some testing of finishing a book marking it complete and it didn't go to the next book unless there's something I'm missing?

**Comment by rasmuslos** [comment]
What is the problem you have with the current view? And did you enable the option in the settings app?

**Comment by zhimiaoli** [comment]
for podcast library, this view will display queued eposides.

**Comment by gh0sti** [comment]
Alright I'll do my best to explain. 

1. When trying to finish a book in the series is it supposed to play the next book via streaming or download the next book then play? When I finish a book here it doesn't go to the next one. 

https://github.com/user-attachments/assets/35f9898e-d9f8-4385-baf1-2d83db457002

1.A Side issues here, am I not able to drag the progress bar to go up and down a track? I feel I should be able to grab the track progress to slide right to go farther in the book or slide left to go back. Example shown in Apple Music. 
https://github.com/user-attachments/assets/02207d2b-d6b0-41dc-b356-ecd238df9ce6

2. I think when we open the queue button it should first go to the chapter/track of the book. Slide left to go to the book serie queue, then slide left again for the bookmark. Maybe add icons to each little subpage. Example icons

Another example view from iOS music the shuffle, repeat, and loop icons in this view could instead be the track/chapter, series, and bookmark
![image](https://github.com/user-attachments/assets/ec15127f-0129-4256-ad32-4b9d96b33556)

Chapter icon
![image](https://github.com/user-attachments/assets/0cefaa9c-4e13-4e4e-9032-8ff62bf0ba45)

Series icon

https://www.svgrepo.com/show/95535/serialized-books.svg

Bookmark icon which seems self explanatory. 
![image](https://github.com/user-attachments/assets/830fe133-af77-412c-8c32-78637636f6ff)

**Comment by gh0sti** [comment]
@rasmuslos, I hope my examples were good and the issues I'm seeing are reproducible. Let me know if you need more details; maybe we could chat more on Discord.

**Comment by rasmuslos** [comment]
I think I get what you mean and I updated the sheet to paginate horizontally. The update should be available soon. Also marking an items as finished will now advance the audio player

**Comment by gh0sti** [comment]
> I think I get what you mean and I updated the sheet to paginate horizontally. The update should be available soon. Also marking an items as finished will now advance the audio player

AWESOME thank you so much for this update I appreciate it, I am liking the changes. 

I didn't see that you added a lock seek bar as a option. That's a nice feature so thanks for looking into this feedback, this has been awesome working with you on improving this app.
