### ISSUE TITLE
[Feature Request] Allow to set sleep timer after given number of chapters

### ISSUE THREAD

**Issue by CZ-DannyK** [rasmuslos/ShelfPlayer#145]
Hello,

i would like to ask for small additional feature for sleep timer. Right now there is only possible to set either "End of chapter" or specified amount of time. And i would really like additional option for "After number of chapters", where i could select how many chapters i want to listen before sleep. Timer options are not good for me as i dont like to end in the middle of chapter and would rather listen to the end, but right now its only for current one.

Thanks for great app and i hope i will see this feature in near future :) 

Daniel

**Comment by rasmuslos** [comment]
Will be available in 2.5.0.Will be available in 2.5.0.
