### ISSUE TITLE
[Feature Request] Show progress percentage

### ISSUE THREAD

**Issue by agraceau** [rasmuslos/ShelfPlayer#154]
Can you please add an option to show the progress through an audiobook as the percentage? I can see this is available in Audiobookshelf. It makes it super easy to update my GoodReads progress. Thanks!!

**Comment by gh0sti** [comment]
> Can you please add an option to show the progress through an audiobook as the percentage? I can see this is available in Audiobookshelf. It makes it super easy to update my GoodReads progress. Thanks!!

Show progress in % in the settings app

![image](https://github.com/user-attachments/assets/6f5ba5df-4c81-4ca4-b126-d408d890ec6c)

**Comment by agraceau** [comment]
Wasn't aware this was an option sorry, thanks!
