### ISSUE TITLE
Allow grouping/collapsing by series on list views

### ISSUE THREAD

**Issue by vicegold** [rasmuslos/ShelfPlayer#155]
The ABS web interface allows you to have series grouped in the library view, would it be possible to allow that on ShelfPlayer as well? When you have a series with hundreds of books it's a bit annoying to have them all show directly in the library.

Here's a quick mockup which doesn't look good, but just to get the idea
![series-in-library](https://github.com/user-attachments/assets/41db67c5-84cb-4e53-9f88-8cddd5b69cbd)

Here's how ABS does it
<img width="549" alt="CleanShot 2024-10-31 at 16 30 15@2x" src="https://github.com/user-attachments/assets/079b1810-8ae5-40b5-ba83-a6af8c6e97ea">

**Comment by vicegold** [comment]
@rasmuslos Looks great, thank you! One thing I've noticed is, that when a series has more than 10 books it still says 10 books, instead of 230 books etc.
![CleanShot 2024-11-19 at 18 49 29@2x](https://github.com/user-attachments/assets/4a0e9f9e-ef78-472e-a746-51210a714e37)

**Comment by rasmuslos** [comment]
Fixed 👍
