### ISSUE TITLE
Can't open authors when a book has multiple authors

### ISSUE THREAD

**Issue by vicegold** [rasmuslos/ShelfPlayer#157]
When you tap on the Author line in the book details and the book has multiple authors the app always just randomizes which detail page it will open, I would like to be able to tap the names individually.

<img width="213" alt="CleanShot 2024-10-31 at 16 33 23@2x" src="https://github.com/user-attachments/assets/048e00aa-f985-48f9-94ed-7b805c95a4d4">

**Comment by rasmuslos** [comment]
Fixed in https://github.com/rasmuslos/ShelfPlayer
