### ISSUE TITLE
New Build?

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#16]
Any chance we can get a new build with the recent changes you added. Your tags are off you have 2.0.7 on GitHub but the most recent build number is 2.1.0

![image](https://github.com/rasmuslos/ShelfPlayer/assets/4202657/63fa3001-a747-48f8-a26c-38c5fd3872b5)

**Comment by rasmuslos** [comment]
I know, I accidentally create the wrong Git tag. I have released a new build with some QoL improvements included
