### ISSUE TITLE
Update contribution instructions

### ISSUE THREAD

**Issue by AlexGustafsson** [rasmuslos/ShelfPlayer#160]
I tried to build the app according to the README, but there were few additional changes I needed to do before it worked:

- Remove Siri from the signing & capabilities settings - just changing the enable all build flag wasn't enough
- Remove carplay from entitlements
- Change identifier in PersistenceManager.swift (hardcoded bundle id)

Also, it seems the localization docs in the README are out of date (there's only one `Localizable.xcstring` file now?).

**Comment by rasmuslos** [comment]
Thank you for your feedback! I added an alternative set of entitlements which you can switch to by adding `CODE_SIGN_ENTITLEMENTS = Configuration/Alternative.entitlements` to your Debug.xcconfig. I also fixed the `ENABLE_ALL_FEATURES` flag to properly change disable the group container.
