### ISSUE TITLE
Author and Series view jittery when scrolling

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#163]
Any chance we can have those views smoothed out when scrolling on the 120hz phone screens?

2.5.0 (490) iOS 18.1 15PM

**Comment by rasmuslos** [comment]
I recently found a way to enable 120fps in SwiftUI, should be available soon.

**Comment by gh0sti** [comment]
> I recently found a way to enable 120fps in SwiftUI, should be available soon.

Doesn't seem to be fixed in build 497 latest TestFlight. Still jittery on 120hz display when scrolling.

**Comment by rasmuslos** [comment]
Can you provide a video?

**Comment by gh0sti** [comment]
> Can you provide a video?

You can see it hitching as it scrolls. 

https://github.com/user-attachments/assets/42759e96-60f1-4a82-b23f-f7a3065f2bf2
