### ISSUE TITLE
Add docs on how to use Siri with Shelfplayer

### ISSUE THREAD

**Issue by sarg3nt** [rasmuslos/ShelfPlayer#165]
I've been trying to figure out how to use Siri with Shelfplayer and am not having any luck.

I just upgraded to 2.5.0

I've tried "Siri, play my book" and "Siri, play Shelfplayer" but neither works. The first tries to open Audible. 

Some docs in the `README.md` would be great!

**Comment by rasmuslos** [comment]
I will try to add an explanation to the app.
