### ISSUE TITLE
[Feature request] Sleep timer - End of chapter

### ISSUE THREAD

**Issue by Tom1206** [rasmuslos/ShelfPlayer#17]
I would love to have an _end of chapter_ option in the sleep timer. I think it is a common behaviour to end a reading session (be it on paper or audio) at the end of a chapter, so it would be really useful in the app.

![IMG_92304017016D-1](https://github.com/rasmuslos/ShelfPlayer/assets/10849079/3c64b7e1-55cb-4f0e-8bed-fadaf1ff766a)

**Comment by rasmuslos** [comment]
Added in https://github.com/rasmuslos/ShelfPlayer/commit/cf43a00d4e96badc842feaca99ef8143cb6ec7c3
Please not that you have to have the chapter track option enabled in settings for this to show up

**Comment by Tom1206** [comment]
Woah you're fast! 🚀 Amazing thank you
