### ISSUE TITLE
Server domain issue

### ISSUE THREAD

**Issue by lamons** [rasmuslos/ShelfPlayer#170]
Context:
- ShelfPlayer: 2.5.1 (517)
- ABS v2.17.2
- iOS 18.1

Quite a strange issue, but I was trying to connect to my ABS server today, and kept getting “server not found” error immidiately (my server domain is https://audiobookshelf.xxxxx.place). While I tested browser access from the same iPhone, from other devices in the same network.. they all worked. 

I then did some network diagnosis and found that ShelfPlayer had not even sent out any request to my server. Even when I typed https://google.com it would try connect to Google. Both "https://audiobookshelf.xxxxx.place" and "https://audiobookshelf.xxxxx.place/" did not work. However, finally I tried "https://audiobookshelf.xxxxx.place/#" and it somehow went through and successfully set up. 

Not sure what was actually the issue, maybe ShelfPlayer did not think some of less common domain suffixes are valid domains so rejected them without trying to connect?

**Comment by rasmuslos** [comment]
Did you use a trailing slash while entering the URL?
