### ISSUE TITLE
Remember last CarPlay library

### ISSUE THREAD

**Issue by jessearmstrong** [rasmuslos/ShelfPlayer#171]
The new CarPlay app is nice, but whenever I launch it in my car the screen is always on offline and there doesn't seem to be any sorting by recent on that view. I have to tap on the online tab and select my library again (I have 5 set up) where I can see the titles sorted by recent. I am not sure what the designed behavior is, but it seemed like a bug to me that it was offline when I launch it and that that sorting on that page doesn't appear to be by recent playback. It would be nice if the app defaulted to online and remembered my last library so I don't have to select it each time. Nice update otherwise!

**Comment by rasmuslos** [comment]
You can select a different sort order in the iOS app when you go offline. It is shared between both apps. I will look into implementing a system that will remember your last library!

**Comment by rasmuslos** [comment]
Can you send me an E-Mail to git@rfk.io from the Adress you use for iTunes so that I you can test this before release?
