### ISSUE TITLE
Unable to connect to server. 

### ISSUE THREAD

**Issue by DCActual** [rasmuslos/ShelfPlayer#173]
When I enter the ip address of my server, on the local network right now, I am just getting a message that says server not found. 

Sorry I don't have more details, but I'm not getting any other error messages. 

I can access the web interface of my server on my iPhone via Firefox and Safari, and was able to get Plappa setup. But for some reason ShelfPlayer on the same iPhone can't see the server.

**Comment by DCActual** [comment]
My server doesn't show any connection attempt. Shelf Player has access to the local network.

**Comment by rasmuslos** [comment]
Did you press allow on a prompt that requested access to your local network?

**Comment by DCActual** [comment]
Yes I did. Verified in the settings that it has access to the local network.

**Comment by DCActual** [comment]
ABS is running in a Docker container if that matters, and isn't putting anything in the log file when I try and connect.

**Comment by DCActual** [comment]
A series of reboots on my phone and server and it is connecting. Not sure what actually fixed it.
