### ISSUE TITLE
[Bug] Low resolution covers

### ISSUE THREAD

**Issue by Tom1206** [rasmuslos/ShelfPlayer#18]
The covers throughout the app have a visible low resolution, lower than Audiobookshelf and competing apps. This is most visible on the now player screen. Audiobookshelf has a really good metadata editor, with integrated cover art search engine. I think this is important to preserve the hard work we put into properly cataloging and illustrating our library, especially in a native application.

**Comment by rasmuslos** [comment]
I seems like ABS defaults to 400x400 covers, I have bumped the resolution to 1000x1000 in https://github.com/rasmuslos/ShelfPlayer/commit/89d103abfbf1d634b661db28fb19a840b9824794

**Comment by Tom1206** [comment]
Thank you very much!
