### ISSUE TITLE
[Feature Request] Configure Podcast Downloads

### ISSUE THREAD

**Issue by PhantomPhoton** [rasmuslos/ShelfPlayer#180]
Thank you for all the hardwork on the app. I have a number of podcasts that are type `Serial` and I want to listen to them in publishing order, not latest. I don't see a way to configure the podcast downloads to download and play from the oldest to newest. Can you please add this support.

**Comment by rasmuslos** [comment]
Change the episode sort order, it is used by the auto download feature.

**Comment by rasmuslos** [comment]
You can change the sort order here:

![IMG_1682](https://github.com/user-attachments/assets/10575e14-1630-4427-ba2b-f0c7a2141195)
![IMG_1684](https://github.com/user-attachments/assets/e7496301-308c-4861-889c-921ea5cda5af)
