### ISSUE TITLE
[Feature Request] Sort and play podcasts oldest to newest.

### ISSUE THREAD

**Issue by adamclaxon** [rasmuslos/ShelfPlayer#185]
A large number of my favorite podcasts are serialized fiction, and while I enjoy this app for the few podcasts that I'm fully caught up on, it's challenging to use it for podcasts where I'm far behind or even starting from episode 1. The ability to display, play, and maintain sorting episodes oldest to newest would make the app much more useable in these scenarios.

**Comment by rasmuslos** [comment]
You can change the sort order from the podcast view. Press "all episodes" and then the icon in the top tight hand corner.
