### ISSUE TITLE
[Feature request] Default order a series by book order in the series

### ISSUE THREAD

**Issue by Tom1206** [rasmuslos/ShelfPlayer#19]
I dont think there is a way to order a series by book order in the series (release date is not reliable for this, depending on the source). I think this should be the default order, it make sense for a series. This is already present in Audiobookshelf.

![CleanShot 2024-01-23 at 10 40 00@2x](https://github.com/rasmuslos/ShelfPlayer/assets/10849079/a2441991-fd29-4506-a34f-c8ea3788a8b6)
![IMG_5E43601E1A64-1](https://github.com/rasmuslos/ShelfPlayer/assets/10849079/25cbba34-daba-413f-8e8f-6745e385793f)

**Comment by rasmuslos** [comment]
There was already an issue for this, see https://github.com/rasmuslos/ShelfPlayer/issues/14
But defaulting to the series sort order is a good idea, has been added in https://github.com/rasmuslos/ShelfPlayer/commit/5eecd9774cb7c646b41eee69234d3fba367faf67

**Comment by Tom1206** [comment]
Sorry for the duplicate, I guess I checked the closed issues to fast. Thank you for adding the default order
