### ISSUE TITLE
App crashes signing in

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#20]
2.1.2 brought back the issue of signing into the app crashes the app. Might be Siri intents?

**Comment by rasmuslos** [comment]
That could be the case, maybe requesting the permission to enable the Siri integration causes the crash, this is the only thing that is invoked after login

**Comment by rasmuslos** [comment]
Please try this version, it does not request Siri authorization

[ShelfPlayer.ipa.zip](https://github.com/rasmuslos/ShelfPlayer/files/14024340/ShelfPlayer.ipa.zip)

**Comment by gh0sti** [comment]
> That could be the case, maybe requesting the permission to enable the Siri integration causes the crash, this is the only thing that is invoked after login

another app I sideload is provenance using sidestore. When I sideload provenance it will ask me to remove the spotlight and widget app ids

**Comment by gh0sti** [comment]
> Please try this version, it does not request Siri authorization
> 
> [ShelfPlayer.ipa.zip](https://github.com/rasmuslos/ShelfPlayer/files/14024340/ShelfPlayer.ipa.zip)

yea that fixed signing in and crashing by removing siri auth right away.

**Comment by gh0sti** [comment]
> That could be the case, maybe requesting the permission to enable the Siri integration causes the crash, this is the only thing that is invoked after login

would it make sense to try to see after signing in to your server that a popup appears to allow siri interaction and maybe adding that delay would allow users to sign in turn on siri and then have the app work?

**Comment by rasmuslos** [comment]
> > That could be the case, maybe requesting the permission to enable the Siri integration causes the crash, this is the only thing that is invoked after login
> 
> another app I sideload is provenance using sidestore. When I sideload provenance it will ask me to remove the spotlight and widget app ids

This should also happen with this app. it is also encouraged, because they will not work as expected.

> > That could be the case, maybe requesting the permission to enable the Siri integration causes the crash, this is the only thing that is invoked after login
> 
> would it make sense to try to see after signing in to your server that a popup appears to allow siri interaction and maybe adding that delay would allow users to sign in turn on siri and then have the app work?

That great, because the same crash occurred in AmpFin, and I did not know it came from this. There is already a popup, but it is provided by the system, and if the app is not signed by a member of the apple developer program the app will crash. I will just remove it in the side loaded version.

**Comment by gh0sti** [comment]
Makes most sense to have siri intents disabled for sideloaded version of shelfplayer until you can get it in the appstore/testflight. Looking forward to seeing it in the store/testflight soon hope you can get it through. Somehow Prologue dev was able to get his app in the store which is very similar to ShelfPlayer. If you want to update the release ipa to remove siri that will work for us sideloaders.

**Comment by rasmuslos** [comment]
This release should fix this: https://github.com/rasmuslos/ShelfPlayer/releases/tag/v2.1.3
