### ISSUE TITLE
[Feature Request] Filter by book genre.

### ISSUE THREAD

**Issue by noneme** [rasmuslos/ShelfPlayer#21]
Is it possible to add filtering of books by genre? sorely missed😀

**Comment by rasmuslos** [comment]
It is an interesting idea, and I have an idea, but this might take some time

**Comment by rasmuslos** [comment]
So I actually experimented with a pill design bellow the navigation bar but sadly it did not really work because SwiftUI insets are shit. So I added a sheet. Not as good as I hoped, but it work
