### ISSUE TITLE
Sort by correct series sequence number

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#22]
I see you added sort by series number however in ABS I have each book in a series starting with 1,2,3 ect. What I'm seeing here is SP is sorting by the first number then proceeding 1,10,11,12,2,20

If we can get the sort by correct that would be great!

![image](https://github.com/rasmuslos/ShelfPlayer/assets/4202657/04238c16-c0de-4fd6-a90b-2e7c95100aae)
![image](https://github.com/rasmuslos/ShelfPlayer/assets/4202657/cd38a860-da73-4ef4-939f-e8317d9c58c3)

**Comment by gh0sti** [comment]
Here is my sequence ordering on ABS

![image](https://github.com/rasmuslos/ShelfPlayer/assets/4202657/efcdc78a-012d-44c3-b88d-03b3b1c14023)

![image](https://github.com/rasmuslos/ShelfPlayer/assets/4202657/db1f8497-137b-4d6d-bd1a-67b747266ce6)

**Comment by gh0sti** [comment]
Something to do with Array sort from a quick search. I remember doing some of that in college but I can't code worth shit anymore.

**Comment by rasmuslos** [comment]
The sort function now uses `localizedStandardCompare`, this should fix this https://github.com/rasmuslos/ShelfPlayer/commit/e636e8924999e092a8db57c1653b41655c8cfb1e

**Comment by rasmuslos** [comment]
I will release a new build in the next few days

**Comment by gh0sti** [comment]
> The sort function now uses `localizedStandardCompare`, this should fix this https://github.com/rasmuslos/ShelfPlayer/commit/e636e8924999e092a8db57c1653b41655c8cfb1e

That solution did not fix the issue.

**Comment by rasmuslos** [comment]
Sorry, I forgot to add this function to the series sort function, I added it to all the other ones but not this one

**Comment by gh0sti** [comment]
> Sorry, I forgot to add this function to the series sort function, I added it to all the other ones but not this one

thanks looking forward to the next build to see this resolved.
