### ISSUE TITLE
[Feature Request] Allow multiple/alternative servers with "fast switching" between them.

### ISSUE THREAD

**Issue by tehguitarist** [rasmuslos/ShelfPlayer#26]
Another low priority request but I guess there are two use cases for this request:

1. Someone hosts their own server, but also has a friend with a server they connect to as well.

2. The ability to connect to a local IP address when at home (for faster speeds, and if loopback configuration is out of the person's ability, or complicated by the use of VPN's) but an external URL when out of home. This is likely the more common use case for my request. I'm not sure if ABS reports a UUID or similar, but obviously the ability to seamlessly move between the two and still update progress on downloaded books (despite changing between local and external addresses) would be nice.

I guess for the second use case, a potential automation would be 
```
IF device is on "My-Wi-Fi SSID" THEN use 192.168.0.2 server; 
ELSE use https://abs.server.com;
```

**Comment by rasmuslos** [comment]
Support for multiple servers is not planned. Using different IP-addresses for different networks might get added, but not in the near future

**Comment by rasmuslos** [comment]
Some links for future reference:
https://developer.apple.com/documentation/networkextension/nehotspotnetwork/3666511-fetchcurrent
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_wifi-info

**Comment by bemble** [comment]
Is there any “profile on the same server” feature considered?
My use-case: I use my profile for my audio books and we have also a shared account with my wife for the kids, to keep the progression independently from who is playing the book (mostly in the car).

**Comment by rasmuslos** [comment]
I will try to add this functionality, it should be possible.

**Comment by rasmuslos** [comment]
Closing this in favor of #166
