### ISSUE TITLE
Can't login with ABS

### ISSUE THREAD

**Issue by seannymurrs** [rasmuslos/ShelfPlayer#27]
I recently installed ShelfPlayer (sideloaded via IPA on releases page). When I try to sign in, I get the error "Audiobookshelf server not found" on my iPhone. I've confirmed that the URL/port is correct (and is the same that is used for the official ABS app). I'm not sure where to go from here in terms of troubleshooting.

**Comment by gh0sti** [comment]
Are you self hosting or using a3rd party?

**Comment by seannymurrs** [comment]
> Are you self hosting or using a3rd party?

Self hosting on my mac Mini via Docker. I tried using both my mac's IP address and port when connected via wifi as well as using the dynamic DNS hostname I have set up when connected via cellular. Neither worked (but both work via the official app and the web UI).

**Comment by gh0sti** [comment]
I don't think you need the port number in the url. 

You need to make sure it's 

https://xxx.xxx.xxx.xxx/

Try adding that / at the end?

**Comment by seannymurrs** [comment]
> I don't think you need the port number in the url.
> 
> You need to make sure it's
> 
> https://xxx.xxx.xxx.xxx/
> 
> Try adding that / at the end?

Tried that, still getting the same result.

**Comment by gh0sti** [comment]
I'm not sure how else to troubleshoot this it has to be an issue of how your abs is exposed to the internet. Docker I believe has 2 different ports a forwarding and the port that the container is set up on. I would try both ports maybe or the password to your abs server is incorrect.

**Comment by seannymurrs** [comment]
> I'm not sure how else to troubleshoot this it has to be an issue of how your abs is exposed to the internet. Docker I believe has 2 different ports a forwarding and the port that the container is set up on. I would try both ports maybe or the password to your abs server is incorrect.

I'll give it a try. The thing that's most confusing to me is the official iOS app can access the server with no problems. Same for the webui in a browser. I'm not sure why I'd need to enter anything different for ShelfPlayer than what I use for either of those two.

**Comment by noneme** [comment]
hmmm.. generally strange behavior. I also use ABS deployed in docket on an external server and there have been no problems with authorization since the first version 🤔

**Comment by gh0sti** [comment]
The only other thing is how server connection string logic is being handled by @rasmuslos if port number ':xxxx' isn't supported? 
example https:// abs.com:4531/ ?

**Comment by rasmuslos** [comment]
Are you using a self signed ssl certificate? You should also go to the settings app and check if ShelfPlayer has access to your local network. This is required when connecting to an IP reserved for private use (I think 10.0.0.0/8 & 192.0.0.0/24)

**Comment by seannymurrs** [comment]
> Are you using a self signed ssl certificate? You should also go to the settings app and check if ShelfPlayer has access to your local network. This is required when connecting to an IP reserved for private use (I think 10.0.0.0/8 & 192.0.0.0/24)

No ssl certificate (accessing using http). I checked for local network access, and ShelfPlayer isn't on the list. I never got a popup asking for access, so I'm not sure how to authorize it.

**Comment by gh0sti** [comment]
> > Are you using a self signed ssl certificate? You should also go to the settings app and check if ShelfPlayer has access to your local network. This is required when connecting to an IP reserved for private use (I think 10.0.0.0/8 & 192.0.0.0/24)
> 
> No ssl certificate (accessing using http). I checked for local network access, and ShelfPlayer isn't on the list. I never got a popup asking for access, so I'm not sure how to authorize it.

Settings App -> Privacy -> Local Network -> toggle is where the App would be however... @rasmuslos I don't see shelfplayer there either requesting access to Local Network. Don't you need to add that as a permission request when building the app from xcode?

**Comment by rasmuslos** [comment]
Normally the system shows the popup when the app makes a request to any of these IPs. I can try to find out if I can trigger it manually

**Comment by seannymurrs** [comment]
Interesting update. When I got home, I tried connecting using the IP address and port for the Mac running ABS. I got the local network pop up, and then it worked. The problem is, I still get the error when using either my WAN ip or DDNS address I have set up. Since ABS can be accessed from outside my home network via both the official app and the WEB UI, I feel like the issue at least partially has something to do with ShelfPlayer. Would love any suggestions on how to test from here.

**Comment by rasmuslos** [comment]
> Interesting update. When I got home, I tried connecting using the IP address and port for the Mac running ABS. I got the local network pop up, and then it worked. The problem is, I still get the error when using either my WAN ip or DDNS address I have set up. Since ABS can be accessed from outside my home network via both the official app and the WEB UI, I feel like the issue at least partially has something to do with ShelfPlayer. Would love any suggestions on how to test from here.

How is the traffic encrypted when you are connecting to ABS outside of your local network?

**Comment by seannymurrs** [comment]
Not sure. I didn't set up anything specific.

**Comment by rasmuslos** [comment]
Are you using `http` or `https`. If you are using `https`, is the certificate self signed?

**Comment by seannymurrs** [comment]
http.

**Comment by rasmuslos** [comment]
What is the error you get when you try to connect to your server?

**Comment by seannymurrs** [comment]
Audiobookshelf server not found. It pops up immediately (no spinning loading wheel or anything like it's trying to connect). 

![IMG_4703](https://github.com/rasmuslos/ShelfPlayer/assets/6283769/17fef215-78f2-4268-90b6-58397a9a182d)

**Comment by gh0sti** [comment]
> Audiobookshelf server not found. It pops up immediately (no spinning loading wheel or anything like it's trying to connect). 
> 
> 
> 
> ![IMG_4703](https://github.com/rasmuslos/ShelfPlayer/assets/6283769/17fef215-78f2-4268-90b6-58397a9a182d)
> 
> 

Copy and paste what you have there into Safari and see if it loads.

**Comment by seannymurrs** [comment]
Yes, it loads just fine. Same with the official ABS app. ShelfPlayer is the only place where it doesn't work.

**Comment by rasmuslos** [comment]
Is this the same server that works on your local network or a different one?

**Comment by seannymurrs** [comment]
> Is this the same server that works on your local network or a different one?

It's the same server. The only difference is I used the IP address of the machine running ABS when I was able to successfully connect locally.

**Comment by rasmuslos** [comment]
That is really strange. Do you have any additional security measures in place (Fail2Ban, IP-Whitelists, VPN, etc)?

Also you should really not expose ABS to the internet without an SSL certificate, even if it is self signed. Truly anyone with a bit of technical knowledge, that is connected to the same WIFI network, can read all your traffic, including your library, the raw audio files and even your token, basically a password that the app uses to authenticate in you, so they could even log into your account.

**Comment by seannymurrs** [comment]
> That is really strange. Do you have any additional security measures in place (Fail2Ban, IP-Whitelists, VPN, etc)?

No additional security measures. I'm genuinely stumped.

>Also you should really not expose ABS to the internet without an SSL certificate, even if it is self signed. Truly anyone with a bit of technical knowledge, that is connected to the same WIFI network, can read all your traffic, including your library, the raw audio files and even your token, basically a password that the app uses to authenticate in you, so they could even log into your account.

I plan on adding SSL eventually. I just started setting up ABS last week, and I don't even have the server up and running 24/7 yet, but thank you for the recommendation.

**Comment by rasmuslos** [comment]
> No additional security measures. I'm genuinely stumped.

Then I am out of ideas. Try adding a SSL certificate, I think I read somewhere that apple requires all connections to domain names to be encrypted, but I could not find anything to confirm this. But at this point I am grasping at straws...

**Comment by seannymurrs** [comment]
> > No additional security measures. I'm genuinely stumped.
> 
> Then I am out of ideas. Try adding a SSL certificate, I think I read somewhere that apple requires all connections to domain names to be encrypted, but I could not find anything to confirm this. But at this point I am grasping at straws...

Will do. I'll report back whether that changes anything.

**Comment by seannymurrs** [comment]
I think it must be an issue with the app not being able to access servers that aren't secured via http. I haven't set up SLL yet, having some issues figuring out how to do it with my setup, but I did spin up a new server on a remote seedbox I have. ShelfPlayer couldn't access this one either (also didn't have SSL), but I can access it just fine using safari on my iPhone.

**Comment by gh0sti** [comment]
> I think it must be an issue with the app not being able to access servers that aren't secured via http. I haven't set up SLL yet, having some issues figuring out how to do it with my setup, but I did spin up a new server on a remote seedbox I have. ShelfPlayer couldn't access this one either (also didn't have SSL), but I can access it just fine using safari on my iPhone. 

Get nginx setup for proxy ssl.

**Comment by seannymurrs** [comment]
Finally got ssl set up via nginx proxy manager. Can confirm I'm still getting the exact same behavior in SwiftPlayer. Also confirmed I can access the server fine via safari and the official app.

**Comment by seannymurrs** [comment]
Ok, I finally got it working, but I still have no idea what the issue was. I have been meaning to transfer my domain name away from Google Domains since they're going away soon anyway. I went ahead and did that tonight and switched it over to CloudFlare. After doing so, it started working (still using SSL via NPM).

**Comment by rasmuslos** [comment]
That is really strange. The only thing I can think of are some WAF rules google applies but I don’t think we can know for sure.
