### ISSUE TITLE
[Bug] Sleep timer defaulting to 2 hours no matter which value is selected.

### ISSUE THREAD

**Issue by tehguitarist** [rasmuslos/ShelfPlayer#29]
This is on the latest version built from source (with the image cache fix being that most recent commit)

the exception to this is end of chapter, which seems to work correctly, though it doesn’t adjust if you skip forward or backwards through the chapter. It stays at the initial value.

I’m also not sure if this is related, or intended, but the clear/increase/decrease dialog also “pulses” in brightness. It also disappears when you choose increase or decrease, that might be intended but a confirmation dialogue, or the ability to increment/decrement by more than a minute at a time may be good.

**Comment by rasmuslos** [comment]
Most things should be fixed here: https://github.com/rasmuslos/ShelfPlayer/commit/d3991ab20b18787aee68c51abf6d83d1e4c2cd1b
Also what do you mean with "pulses"? Can you share a screen recording?
I also wanted to keep the menu on screen after the user increments or decrements the timer, but this is one of those things that's just not possible with SwiftUI for unknown reasons...

**Comment by tehguitarist** [comment]
Testing it out and looking good (had to do a completely fresh install for it to work, which is fine). Could a solution for the pop up be a +/- buttons to set the time, with a confirmation or cancel button to lock it in? Or is this a “the pop up can only exist for one click” type of silly limitation.


I’ve attached a video of the pulsing below though. Only seems to happen when an audiobook is playing, when it’s paused it’s fine.
https://github.com/rasmuslos/ShelfPlayer/assets/28495826/8b8768b5-1971-4884-83d7-b2faefc7842c

**Comment by tehguitarist** [comment]
Another thing I noticed is that the text box for the time remaining sometimes goes to … instead of the number of minutes or seconds (when the last 59 seconds counts down it becomes most evident) I’ll attach a screenshot below
![IMG_7732](https://github.com/rasmuslos/ShelfPlayer/assets/28495826/02c968a7-24db-414f-af4a-fe75369716a7)

**Comment by rasmuslos** [comment]
> Testing it out and looking good (had to do a completely fresh install for it to work, which is fine). Could a solution for the pop up be a +/- buttons to set the time, with a confirmation or cancel button to lock it in? Or is this a “the pop up can only exist for one click” type of silly limitation.
> 
> I’ve attached a video of the pulsing below though. Only seems to happen when an audiobook is playing, when it’s paused it’s fine. https://github.com/rasmuslos/ShelfPlayer/assets/28495826/8b8768b5-1971-4884-83d7-b2faefc7842c

Actually I was wrong. You can just set `menuActionDismissBehavior` and it should work.



> Another thing I noticed is that the text box for the time remaining sometimes goes to … instead of the number of minutes or seconds (when the last 59 seconds counts down it becomes most evident) I’ll attach a screenshot below ![IMG_7732](https://private-user-images.githubusercontent.com/28495826/300413265-02c968a7-24db-414f-af4a-fe75369716a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDY2MzgsIm5iZiI6MTcwNjU0NjMzOCwicGF0aCI6Ii8yODQ5NTgyNi8zMDA0MTMyNjUtMDJjOTY4YTctMjRkYi00MTRmLWFmNGEtZmU3NTM2OTcxNmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE2Mzg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZjk1NTVkOTEyMGQyNDhkZTY1YjE0YmFkYWNhMWZmMjgyYTQwNmMzODhhMjgyNjViYzRiOTQ3OTM4NTcxOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IRFkGxu3Miy78THeMFr98ExZnM3RRqZTbQdDMlBSNgc)

I *thought* I had addressed this, but apparently not. But it should be an easy fix
