### ISSUE TITLE
[Feature Request] Fade audio at the end of the sleep timer.

### ISSUE THREAD

**Issue by tehguitarist** [rasmuslos/ShelfPlayer#30]
At the moment, audio just pauses. Having a long fade, 5-10 seconds, would be a more pleasant experience I think.

I guess the natural follow on would be ensuring the saved audio position is the fade start time, not the fade finish time. Though smart rewind also solves that.

**Comment by tehguitarist** [comment]
Hey, this feature has been working great! Only request would be to rewind the audio 10 seconds after the fade, as if you hit play after it stops, it plays from when the fade ended, rather than when the fade stop, resulting in you losing the last couple of words. Not a big deal, it's easy enough to skip back too.

**Comment by rasmuslos** [comment]
I initially thought I would have to update the reporting logic to halt when the sleep timer ends but I it is entirely possible to just seek back when the sleep timer ends. So this is what happens now when smart rewind is enabled (https://github.com/rasmuslos/ShelfPlayer/commit/e2d2ccacf9a8fa1e209f3185d43e27ba8266033b)
