### ISSUE TITLE
[Feature Request] Support OIDC Login

### ISSUE THREAD

**Issue by ipcintron** [rasmuslos/ShelfPlayer#32]
Shelfplayer only supports local accounts. It would be nice to login via an OIDC created account in ABS

**Comment by rasmuslos** [comment]
This is definitely planned, but might take some time

**Comment by sevenlayercookie** [comment]
I'm not getting the option for OIDC login, just the usual username and password. How do I enable this?

**Comment by rasmuslos** [comment]
The update is pending approval from apple and should be released soon

**Comment by sevenlayercookie** [comment]
> The update is pending approval from apple and should be released soon

updated, and was able to successfully login with OIDC once I added the redirect url to ABS settings. Loving the app!
