### ISSUE TITLE
[Feature Request] Centre on currently playing chapter in chapter selection menu.

### ISSUE THREAD

**Issue by tehguitarist** [rasmuslos/ShelfPlayer#33]
Another low priority (but potentially easy to implement) feature request from me. I figured I'd just throw out UX things as I think of them.

This one is around chapter selection on a playing audiobook. Currently, when you open that pop up, it always goes to the beginning of the chapter list.
It would be nice for this to centre on the current chapter so you can move forward or backwards easily, rather than it starting on the current chapter, and having to scroll backwards.
A use case for this is if you fall asleep before a sleep timer ends and you need to go to the previous chapter quickly.

While looking at this, I noticed that the bold font on the current font is quite subtle (on the dark theme at least). Perhaps a grey background highlight might be good to give a more obvious visual indicator without adding additional icons, and still work for both light and dark themes. Alternatively a vertical bar on the left (or right) side, might achieve the same goal.

**Comment by rasmuslos** [comment]
These things actually were on my todo list, I just didn't get around to implement them yet. I also wanted to add some animations everything related to chapters to make them a bit nicer to use

**Comment by rasmuslos** [comment]
Added in https://github.com/rasmuslos/ShelfPlayer/commit/35365bfa96c02df2284df8e6eef540e74b11d617
