### ISSUE TITLE
[Feature Request] separate sort based on view and add sort options in each view

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#36]
I noticed that in an author view or in library view if you set ascending sort all views will sort the same. Is there a way we can have separate sort for each view?

Author page should also get the sort button option in the top right corner. 

![image](https://github.com/rasmuslos/ShelfPlayer/assets/4202657/07c00c66-b0bc-47f7-9e05-5d671bc6213e)

![image](https://github.com/rasmuslos/ShelfPlayer/assets/4202657/9ef18ebc-30b3-4b14-b698-0e8065b62ee4)

**Comment by gh0sti** [comment]
Example: I want my series page to sort by ascending and my library page to sort by descending and to keep those sort options when I view those pages.

**Comment by rasmuslos** [comment]
Any selection (filter & ascending) you make in the series view does not update the global filter settings. And I think it is fine to have the same filter for authors and the library, although the other view could default to `released & ascending` without updating the global filter, too

> Author page should also get the sort button option in the top right corner.

You mean the page that lists all authors?

**Comment by gh0sti** [comment]
> Any selection (filter & ascending) you make in the series view does not update the global filter settings. And I think it is fine to have the same filter for authors and the library, although the other view could default to `released & ascending` without updating the global filter, too
> 
> > Author page should also get the sort button option in the top right corner.
> 
> You mean the page that lists all authors?

I think I was thinking that you could reverse the sort for Author have Z-A instead of A-Z by default. Also for Ascending, when Ascending is toggled it should sort A-Z and 0-9, etc if you Select it Library view sorts Z-A for author instead of A-Z
"Answer: In general terms, Ascending means smallest to largest, 0 to 9, and/or A to Z and Descending means largest to smallest, 9 to 0, and/or Z to A."

I would investigate the logic of how you sort based on Ascending.
https://kb.blackbaud.com/knowledgebase/Article/117098#:~:text=Answer%3A,and%2For%20Z%20to%20A.

**Comment by rasmuslos** [comment]
The problem is, that is made a mistake in the sorting logic, should be an easy fix
