### ISSUE TITLE
[Question] Enable background fetch and background processing?

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#37]
I was looking at xcode while compiling latest build and noticed that background fetch and processing were not toggled. Is that something that should be or would enhance Shelfplayer by having those features toggled? My assumption is then the app can fetch newer updates from the server for potential new books or changes that are made to the server while the app is running in the background. I think this would enable background app refresh?
<img width="385" alt="xcode" src="https://github.com/rasmuslos/ShelfPlayer/assets/4202657/1cf4af32-a14a-4821-acf9-5ecb9c5ca4d5">

https://stackoverflow.com/questions/44238987/what-is-the-different-between-background-task-and-background-fetch-correctly

**Comment by rasmuslos** [comment]
I have already looked into implementing notifications and automatic downloads using background fetch, but you are completely at the mercy of the system, so it would have questionable reliability. But I will probably experiment with this in the future
