### ISSUE TITLE
[Feature Request] Pause audio when map directions are being used

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#38]
I'm not sure if that's a special entitlement you need from Apple to get the ability to pause, spoken audio. I know that's a toggle in Apple Maps app to toggle on pause, spoken audio. That's something that I've noticed with this app is when you are listening to an audiobook, and you have map directions. The audio just goes quieter instead of pausing for spoken directions.

**Comment by rasmuslos** [comment]
Ironically I already did this in AmpFin, I think I mixed the two implementations up, but now they are right
