### ISSUE TITLE
Can't sign into my ABS server on v2.0

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#4]
I sideloaded the app with sidestore and the app crashes immediately after I try to sign in with my server URL and username and password. Now the app won't even launch without crashing.

ABS: v2.6.0 docker

**Comment by rasmuslos** [comment]
How are you logging in, using the local strategy or sso?

**Comment by gh0sti** [comment]
> How are you logging in, using the local strategy or sso?

Local

**Comment by rasmuslos** [comment]
Try reinstalling the app, there has been a change in the underlying architecture to allow app extensions to function properly. Removing all data by uninstalling the app should fix the issue

**Comment by gh0sti** [comment]
> Try reinstalling the app, there has been a change in the underlying architecture to allow app extensions to function properly. Removing all data by uninstalling the app should fix the issue

Did you upload a new build on github? Otherwise can I send you a private video of what happens when I log in and crash the app?

**Comment by rasmuslos** [comment]
You have to uninstall and then reinstall the app to delete all data. There was a change in the underlying database structure without a migration, so the app just crashes. I guess this is the reason why you are experiencing the crash. If this does not solve the issue please run the App using Xcode and provide the log output, otherwise cannot find out why the app behaves this way.

**Comment by gh0sti** [comment]
> You have to uninstall and then reinstall the app to delete all data. There was a change in the underlying database structure without a migration, so the app just crashes. I guess this is the reason why you are experiencing the crash. If this does not solve the issue please run the App using Xcode and provide the log output, otherwise cannot find out why the app behaves this way.

Which I have done. What I'm doing is sideloading the app from SideStore https://sidestore.io/

This allows for sideloading apps on device going forward. Your app crashes right after I sign into my server.

**Comment by gh0sti** [comment]
> hmm... same situation. When installed using SideStore or AltStore, the application crashes.
> 
> When signing and installing an application using SideLoadly, the application also crashes :-(
> 
> When installing the application using XCode (replacing the Bundle Identifer and App Group with your own), the application will generate an error when building
> 
> Thread 1: Fatal error: Unable to find App Group Container in Entitlements: group.io.rfk.shelfplayer)
> 
> 
> 
> ![Снимок экрана 2023-12-24 в 23 48 50](https://github.com/rasmuslos/ShelfPlayer/assets/5063522/07f797d0-9045-4e35-8869-de0ba1846e8c)

I'm glad I'm not the only one.

**Comment by benonymity** [comment]
You have to change the group name in the app config in Xcode, then change the crashing line to reference the new group name and it builds fine.

**Comment by rasmuslos** [comment]
Yes, this is the solution. I put most things related to the database in an app group as data that is stored there is also available in app extensions. This is important for Siri integration, etc.

I have thought about a possible solution over the last few days, but the best thing I could think of is to just not use a shared group when side-loading. Right now the impact would be pretty small, as nothing makes use of the shared data just yet. Also in the future when there is a Siri integration it will not affect anyone that is side-loading, because you have to be a part of the Apple Developer program for Siri to work. Also, most people strip app extensions becuase they count towards the identifier limit of 10. 

Anyone that is part of the Apple Developer programm propably has Xcode installed and can make the required changes themselves. It is sadly [not possible](https://stackoverflow.com/questions/42853052/how-to-get-app-groups-name-programmatically) to get the available app groups programmatically.

**Comment by noneme** [comment]
> You have to change the group name in the app config in Xcode, then change the crashing line to reference the new group name and it builds fine.

yes, it works

**Comment by noneme** [comment]
> Yes, this is the solution. I put most things related to the database in an app group as data that is stored there is also available in app extensions. This is important for Siri integration, etc.
> 
> I have thought about a possible solution over the last few days, but the best thing I could think of is to just not use a shared group when side-loading. Right now the impact would be pretty small, as nothing makes use of the shared data just yet. Also in the future when there is a Siri integration it will not affect most people that are side-loading using AltStore, because you have to be a part of the Apple Developer program for Siri to work. Also, most people strip app extensions becuase they count towards the identifier limit of 10.
> 
> Anyone that is part of the Apple Developer programm propably has Xcode installed and can make the required changes themselves. It is sadly [not possible](https://stackoverflow.com/questions/42853052/how-to-get-app-groups-name-programmatically) to get the available app groups programmatically.

okay! thank you!
What's up with the App Store? ;-)

**Comment by noneme** [comment]
> Yes, this is the solution. I put most things related to the database in an app group as data that is stored there is also available in app extensions. This is important for Siri integration, etc.
> 
> I have thought about a possible solution over the last few days, but the best thing I could think of is to just not use a shared group when side-loading. Right now the impact would be pretty small, as nothing makes use of the shared data just yet. Also in the future when there is a Siri integration it will not affect most people that are side-loading using AltStore, because you have to be a part of the Apple Developer program for Siri to work. Also, most people strip app extensions becuase they count towards the identifier limit of 10.
> 
> Anyone that is part of the Apple Developer programm propably has Xcode installed and can make the required changes themselves. It is sadly [not possible](https://stackoverflow.com/questions/42853052/how-to-get-app-groups-name-programmatically) to get the available app groups programmatically.

problem Thread 1: Fatal error: Unable to find App Group Container in Entitlements: group.io.rfk.shelfplayer)
I decided like this:
<img width="985" alt="Снимок экрана 2023-12-25 в 19 55 05" src="https://github.com/rasmuslos/ShelfPlayer/assets/5063522/0c2a07f4-234e-4417-8dce-cf2d6f61348f">

_https://stackoverflow.com/questions/42853052/how-to-get-app-groups-name-programmatically
https://stackoverflow.com/questions/25897086/obtain-bundle-identifier-programmatically-in-swift_

**Comment by rasmuslos** [comment]
> > Yes, this is the solution. I put most things related to the database in an app group as data that is stored there is also available in app extensions. This is important for Siri integration, etc.
> > I have thought about a possible solution over the last few days, but the best thing I could think of is to just not use a shared group when side-loading. Right now the impact would be pretty small, as nothing makes use of the shared data just yet. Also in the future when there is a Siri integration it will not affect most people that are side-loading using AltStore, because you have to be a part of the Apple Developer program for Siri to work. Also, most people strip app extensions becuase they count towards the identifier limit of 10.
> > Anyone that is part of the Apple Developer programm propably has Xcode installed and can make the required changes themselves. It is sadly [not possible](https://stackoverflow.com/questions/42853052/how-to-get-app-groups-name-programmatically) to get the available app groups programmatically.
> 
> problem Thread 1: Fatal error: Unable to find App Group Container in Entitlements: group.io.rfk.shelfplayer) I decided like this: <img alt="Снимок экрана 2023-12-25 в 19 55 05" width="985" src="https://private-user-images.githubusercontent.com/5063522/292770918-0c2a07f4-234e-4417-8dce-cf2d6f61348f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MjQyMzQsIm5iZiI6MTcwMzUyMzkzNCwicGF0aCI6Ii81MDYzNTIyLzI5Mjc3MDkxOC0wYzJhMDdmNC0yMzRlLTQ0MTctOGRjZS1jZjJkNmY2MTM0OGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjVUMTcwNTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY0ZDMxYTgxZjgxOTEzYjUyOWY2ZGUyZTg4NDY2YmJiZDdlYTU1NTBmNTZjMjk2ZDY0YzhjNmU2YWE4YTU3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TovmCHv7ZWP0gXqms_2Qk6gOfdfsNTdvyPxbSQl8t_k">
> 
> _https://stackoverflow.com/questions/42853052/how-to-get-app-groups-name-programmatically https://stackoverflow.com/questions/25897086/obtain-bundle-identifier-programmatically-in-swift_

I am not quite sure if this will work because I don't know how AltStore changes group identifiers, but I don't think this will work.
Can you send a Screenshot of the "App Groups" section on the "Signing & Capabilities" page in Xcode? All your group identifiers, include the ones made by AltStore should be listed there.

**Comment by rasmuslos** [comment]
> > Yes, this is the solution. I put most things related to the database in an app group as data that is stored there is also available in app extensions. This is important for Siri integration, etc.
> > I have thought about a possible solution over the last few days, but the best thing I could think of is to just not use a shared group when side-loading. Right now the impact would be pretty small, as nothing makes use of the shared data just yet. Also in the future when there is a Siri integration it will not affect most people that are side-loading using AltStore, because you have to be a part of the Apple Developer program for Siri to work. Also, most people strip app extensions becuase they count towards the identifier limit of 10.
> > Anyone that is part of the Apple Developer programm propably has Xcode installed and can make the required changes themselves. It is sadly [not possible](https://stackoverflow.com/questions/42853052/how-to-get-app-groups-name-programmatically) to get the available app groups programmatically.
> 
> okay! thank you! What's up with the App Store? ;-)

<img width="1374" alt="Bildschirmfoto 2023-12-25 um 18 05 21" src="https://github.com/rasmuslos/ShelfPlayer/assets/49640416/51df60ad-e288-44b5-a7dc-d7fb44d7599d">

I would like to know, too...

**Comment by noneme** [comment]
> > > Yes, this is the solution. I put most things related to the database in an app group as data that is stored there is also available in app extensions. This is important for Siri integration, etc.
> > > I have thought about a possible solution over the last few days, but the best thing I could think of is to just not use a shared group when side-loading. Right now the impact would be pretty small, as nothing makes use of the shared data just yet. Also in the future when there is a Siri integration it will not affect most people that are side-loading using AltStore, because you have to be a part of the Apple Developer program for Siri to work. Also, most people strip app extensions becuase they count towards the identifier limit of 10.
> > > Anyone that is part of the Apple Developer programm propably has Xcode installed and can make the required changes themselves. It is sadly [not possible](https://stackoverflow.com/questions/42853052/how-to-get-app-groups-name-programmatically) to get the available app groups programmatically.
> > 
> > 
> > problem Thread 1: Fatal error: Unable to find App Group Container in Entitlements: group.io.rfk.shelfplayer) I decided like this: <img alt="Снимок экрана 2023-12-25 в 19 55 05" width="985" src="https://private-user-images.githubusercontent.com/5063522/292770918-0c2a07f4-234e-4417-8dce-cf2d6f61348f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MjQyMzQsIm5iZiI6MTcwMzUyMzkzNCwicGF0aCI6Ii81MDYzNTIyLzI5Mjc3MDkxOC0wYzJhMDdmNC0yMzRlLTQ0MTctOGRjZS1jZjJkNmY2MTM0OGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjVUMTcwNTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY0ZDMxYTgxZjgxOTEzYjUyOWY2ZGUyZTg4NDY2YmJiZDdlYTU1NTBmNTZjMjk2ZDY0YzhjNmU2YWE4YTU3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TovmCHv7ZWP0gXqms_2Qk6gOfdfsNTdvyPxbSQl8t_k">
> > _https://stackoverflow.com/questions/42853052/how-to-get-app-groups-name-programmatically https://stackoverflow.com/questions/25897086/obtain-bundle-identifier-programmatically-in-swift_
> 
> I am not quite sure if this will work because I don't know how AltStore changes group identifiers, but I don't think this will work. Can you send a Screenshot of the "App Groups" section on the "Signing & Capabilities" page in Xcode? All your group identifiers, include the ones made by AltStore should be listed there.

Certainly:
<img width="907" alt="Снимок экрана 2023-12-25 в 20 14 05" src="https://github.com/rasmuslos/ShelfPlayer/assets/5063522/7b0c2374-eaae-4574-8836-65b4b478df01">

installed using Xcode, works

**Comment by rasmuslos** [comment]
> > > > Yes, this is the solution. I put most things related to the database in an app group as data that is stored there is also available in app extensions. This is important for Siri integration, etc.
> > > > I have thought about a possible solution over the last few days, but the best thing I could think of is to just not use a shared group when side-loading. Right now the impact would be pretty small, as nothing makes use of the shared data just yet. Also in the future when there is a Siri integration it will not affect most people that are side-loading using AltStore, because you have to be a part of the Apple Developer program for Siri to work. Also, most people strip app extensions becuase they count towards the identifier limit of 10.
> > > > Anyone that is part of the Apple Developer programm propably has Xcode installed and can make the required changes themselves. It is sadly [not possible](https://stackoverflow.com/questions/42853052/how-to-get-app-groups-name-programmatically) to get the available app groups programmatically.
> > > 
> > > 
> > > problem Thread 1: Fatal error: Unable to find App Group Container in Entitlements: group.io.rfk.shelfplayer) I decided like this: <img alt="Снимок экрана 2023-12-25 в 19 55 05" width="985" src="https://private-user-images.githubusercontent.com/5063522/292770918-0c2a07f4-234e-4417-8dce-cf2d6f61348f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MjQyMzQsIm5iZiI6MTcwMzUyMzkzNCwicGF0aCI6Ii81MDYzNTIyLzI5Mjc3MDkxOC0wYzJhMDdmNC0yMzRlLTQ0MTctOGRjZS1jZjJkNmY2MTM0OGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjVUMTcwNTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY0ZDMxYTgxZjgxOTEzYjUyOWY2ZGUyZTg4NDY2YmJiZDdlYTU1NTBmNTZjMjk2ZDY0YzhjNmU2YWE4YTU3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TovmCHv7ZWP0gXqms_2Qk6gOfdfsNTdvyPxbSQl8t_k">
> > > _https://stackoverflow.com/questions/42853052/how-to-get-app-groups-name-programmatically https://stackoverflow.com/questions/25897086/obtain-bundle-identifier-programmatically-in-swift_
> > 
> > 
> > I am not quite sure if this will work because I don't know how AltStore changes group identifiers, but I don't think this will work. Can you send a Screenshot of the "App Groups" section on the "Signing & Capabilities" page in Xcode? All your group identifiers, include the ones made by AltStore should be listed there.
> 
> Certainly: <img alt="Снимок экрана 2023-12-25 в 20 14 05" width="907" src="https://private-user-images.githubusercontent.com/5063522/292771664-7b0c2374-eaae-4574-8836-65b4b478df01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MjQ5NzQsIm5iZiI6MTcwMzUyNDY3NCwicGF0aCI6Ii81MDYzNTIyLzI5Mjc3MTY2NC03YjBjMjM3NC1lYWFlLTQ1NzQtODgzNi02NWI0YjQ3OGRmMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjVUMTcxNzU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWJjYzIwOWU3MGE3MjFhNjE5YTY5NWZhZWE0N2YxNzNiMzUyMzhjYzg3NzIxNjZmNzNmMzYyNmJiMDA3ODc1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Gdk70IY96kcPc08Lsr6r0qoRjatZ-q5MpRuwHScE1Wc">
> 
> installed using Xcode, works

Just below that :)

<img width="1728" alt="Bildschirmfoto 2023-12-25 um 18 08 04" src="https://github.com/rasmuslos/ShelfPlayer/assets/49640416/648311be-b763-4777-9b49-ec2a2efd05ee">

**Comment by noneme** [comment]
> Just below that :)

<img width="858" alt="Снимок экрана 2023-12-25 в 20 22 26" src="https://github.com/rasmuslos/ShelfPlayer/assets/5063522/f0597376-1b74-4d54-a704-22004edf6d38">

**Comment by rasmuslos** [comment]
> > Just below that :)
> 
> <img alt="Снимок экрана 2023-12-25 в 20 22 26" width="858" src="https://private-user-images.githubusercontent.com/5063522/292771970-f0597376-1b74-4d54-a704-22004edf6d38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MjUzNzEsIm5iZiI6MTcwMzUyNTA3MSwicGF0aCI6Ii81MDYzNTIyLzI5Mjc3MTk3MC1mMDU5NzM3Ni0xYjc0LTRkNTQtYTcwNC0yMjAwNGVkZjZkMzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjVUMTcyNDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2MzYzk2YThiYmNjMTZhOTkyMDQ2ODFhMmFiMTI3MTJkNDI2NTBkYTA3ZDhkMDcwYWQ4ODMyZmVhOTY2NzFhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u-34wL53bAiBsKm855fwYdTKKcZmYp2FnhRBHXcDGTw">

So it looks like AltStore appends some id (I don't think it's your developer id) to the group id. I will have a look at the AltStore repo to find out if using the bundle identifier is a viable solution, but it might take some time.

**Comment by noneme** [comment]
> So it looks like AltStore appends some id (I don't think it's your developer id) to the group id. I will have a look at the AltStore repo to find out if using the bundle identifier is a viable solution, but it might take some time

ok, but for me it’s not urgent! this is more for research purposes ;-)

**Comment by rasmuslos** [comment]
@noneme @gh0sti can you test this build? It should use the correct group identifier: https://github.com/rasmuslos/ShelfPlayer/releases/tag/v2.0.2

**Comment by gh0sti** [comment]
> @noneme @gh0sti can you test this build? It should use the correct group identifier: https://github.com/rasmuslos/ShelfPlayer/releases/tag/v2.0.2

it worked! thanks I was able to sign in

**Comment by gh0sti** [comment]
This is resolved.

**Comment by rasmuslos** [comment]
Great 👍
