### ISSUE TITLE
General improvements. Smart rewind

### ISSUE THREAD

**Issue by noneme** [rasmuslos/ShelfPlayer#42]
Please add a description of the Smart rewind settings option. otherwise, it is not clear what it means since its action is not obvious to the user.

![image](https://github.com/rasmuslos/ShelfPlayer/assets/5063522/cf31bc9a-47f5-4c24-b877-adc5a016da08)

**Comment by rasmuslos** [comment]
I already wanted to do that, but I could nit find a way to add a footer to a settings item

**Comment by rasmuslos** [comment]
So it is possible but someone forgot to add this to Xcode...
