### ISSUE TITLE
Feature request. Bookmarks

### ISSUE THREAD

**Issue by noneme** [rasmuslos/ShelfPlayer#45]
Feature request. It would be great if there was a “bookmarks” option in the future.

**Comment by rasmuslos** [comment]
Bookmarks may come in the future, but to fully support them a lot would have to be implemented (making them available offline, etc.), so they will probably take some time

**Comment by iamhenry** [comment]
where on your priority list is the bookmark feature even if initially it's offline?

**Comment by rasmuslos** [comment]
Bookmarks would have to work on- and offline. I looked into this before, it should be fairly straightforward to implement, finding a place for them in the UI would probably be the biggest issue. I am currently working on porting AmpFin to the iPad, but I think it shouldn't take too long for this to get implemented.

**Comment by rasmuslos** [comment]
Bookmarks will be in the next update, it should become available during the next week
