### ISSUE TITLE
Error. Rewind in the app.

### ISSUE THREAD

**Issue by noneme** [rasmuslos/ShelfPlayer#46]
Error. Rewinding does not work in the application, while everything is ok on the locked screen.

![image](https://github.com/rasmuslos/ShelfPlayer/assets/5063522/b191ed1a-c6f3-4cc9-a85b-145545d2b92a)

**Comment by noneme** [comment]
ok if yes, but in version 2.2.0 it just doesn't work

**Comment by rasmuslos** [comment]
Yes, I fixed it just today, the fix has not been released yet
