### ISSUE TITLE
[Enhancement] Ability to change playback speed by 0.1x

### ISSUE THREAD

**Issue by PulsarFTW** [rasmuslos/ShelfPlayer#49]
Hey - another suggestion for your consideration!

The ability to change the playback speed by 0.1x increments would be great. This could work in the same way as the sleep timer where you have the option to increase or decrease playback speed by 0.1x as the current 0.25x options are quite big jumps! 

Sorry if the suggestions get annoying! - really loving the app!

**Comment by rasmuslos** [comment]
Thanks a lot! You can now adjust the increment value in the settings app. I have also added some more customizability to the sleep timer.

**Comment by PulsarFTW** [comment]
Awesome - I don't have a Mac so I'll check these out with the next IPA release or when it hits the app store!
