### ISSUE TITLE
server address

### ISSUE THREAD

**Issue by sevenlayercookie** [rasmuslos/ShelfPlayer#50]
Loving the app so far! Digging the label-less vibe, letting the audiobook covers do the talking.

One small QOL enhancement: when you're setting your server address, you have to specifically state http(s)://abs.domain.tld. Would be nice if user enters only abs.domain.tld that ShelfPlayer automatically queries both http:// and https:// for one that gives a valid response, that way user doesn't have to explicitly enter the protocol.

**Comment by rasmuslos** [comment]
Thanks! I have opted to pre-fill the server address with `https://`. This should make it easer to input the server address, without adding complexity to the code.
