### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by slyfoxgh** [rasmuslos/ShelfPlayer#52]
Looking at the screenshots, it seems that there is only white background mode. Can you please add dark mode?

**Comment by tehguitarist** [comment]
There is one currently, seems like it follows the system theme. 

Essentially just black background and appropriate font colours instead.

**Comment by slyfoxgh** [comment]
It will be useful to add a screenshot like that on the front page.

**Comment by gh0sti** [comment]
> It will be useful to add a screenshot like that on the front page.

but the app has built in darkmode which follows system mode. I am sure when he gets the app posted to the app store he might show a screenshot but this request to me doesn't make sense.

**Comment by slyfoxgh** [comment]
You are correct; once the app is in the App Store, perhaps there will be screenshots showing dark mode. Judging from the Githb page screenshots, it loos like there is no dark mode. This request can be closed.

**Comment by rasmuslos** [comment]
I probably have to update the screenshots soon, there were some design changes that should be shown.
When I do that I will include a screenshot in dark mode.
