### ISSUE TITLE
Library switching bug

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#53]
Just bought from the AppStore man I'm excited to see that you finally got it in. 

Library switching I think needs to work with out having to do a pull down refresh

https://github.com/rasmuslos/ShelfPlayer/assets/4202657/2f0dddb4-1665-4c95-a13d-2a78e01fea55

**Comment by slyfoxgh** [comment]
I was about to report a bug that library switching does not work. The refresh should happen instantly without the need to pull down. Also, it took me a while to find the icon to switch the library. The current icon is a bookmark icon rather than a library icon. I think it should be changed as it is not intuitive.

**Comment by rasmuslos** [comment]
I can look into changing it. But for me the switching works automatically, so when does this occur (switching from podcasts -> audiobooks, ...?)

**Comment by rasmuslos** [comment]
Die sit happen when you switch from audiobooks -> audiobooks but not when you go from audiobooks -> podcast or the other way around?

**Comment by gh0sti** [comment]
> Die sit happen when you switch from audiobooks -> audiobooks but not when you go from audiobooks -> podcast or the other way around?

In the vid that I sent I went from Audiobooks to Podcasts which glitched and I had to refresh.

**Comment by rasmuslos** [comment]
> > Die sit happen when you switch from audiobooks -> audiobooks but not when you go from audiobooks -> podcast or the other way around?
> 
> In the vid that I sent I went from Audiobooks to Podcasts which glitched and I had to refresh.

I found a solution, the fix will hopefully be available soon

**Comment by rasmuslos** [comment]
I think attaching a tip to the switch library button should work in the meantime

**Comment by slyfoxgh** [comment]
I have eight different libraries. There is more than Audiobooks and Podcasts :) Fiction, Nonfiction, Pdocasts, Full-Cast, ...

Please consider changing the icon from the Bookmark icon to an icon that looks more like a Library.

**Comment by rasmuslos** [comment]
I have submitted the update to apple, it might take a few days before they approve it...

What about this icon?:

<img width="1728" alt="Bildschirmfoto 2024-03-14 um 17 27 04" src="https://github.com/rasmuslos/ShelfPlayer/assets/49640416/768e5cf2-e765-45de-9b5c-9a53d8023f7b">

**Comment by slyfoxgh** [comment]
Yes, the books stack icon makes more sense.
