### ISSUE TITLE
Can't login with Tailscale Address

### ISSUE THREAD

**Issue by JBaby9783** [rasmuslos/ShelfPlayer#55]
I can and do login to ABS in the app and on the web with my Tailscale address. Shelfplayer keeps saying ABS server not found.

**Comment by rasmuslos** [comment]
Can you login into the official app. And do you use OpenID connect?

**Comment by rasmuslos** [comment]
Can you share the Tailscale debug log? You should be able to create it in the Tailscale app.

**Comment by JBaby9783** [comment]
I can connect with the official app. I'm not using OpenID. I have no idea where to find the debug log in Tailscale.
