### ISSUE TITLE
Feature request: Support cover art that isn't 1:1

### ISSUE THREAD

**Issue by alehel** [rasmuslos/ShelfPlayer#56]
I have a few audiobooks that use traditional book covers rather than 1:1 covers. These are cropped by ShelfPlayer. Would be great if these could simply be displayed uncropped, as-is (preferably without filling in the sides with some blurred colour. 

<img width="400" alt="Screenshot 2024-03-14 at 12 18 26" src="https://github.com/rasmuslos/ShelfPlayer/assets/22277624/8b41d812-5ebf-4769-a195-98bcc47a6a0a">

**Comment by rasmuslos** [comment]
I will take a look at this, but I can not guarantee that it will come in the near future. Every image in the app is expected to be in 1:1 aspect ratio, so making sure that the layout will not break is going to be quite challenging.
