### ISSUE TITLE
Feature request: Scroll long podcast episode names

### ISSUE THREAD

**Issue by alehel** [rasmuslos/ShelfPlayer#58]
Currently, if a podcast episode has a long name, the end just gets cut off. 

<img width="400" alt="Screenshot 2024-03-14 at 12 28 50" src="https://github.com/rasmuslos/ShelfPlayer/assets/22277624/d5d5836d-8718-4c8a-abcc-f4a4ca88fbb3">

In the example above, this means I don't really know which episode is which of the Derelict podcast. It would be nice if these titles could auto scroll to reveal the whole text.

**Comment by rasmuslos** [comment]
MacOS is not officially supported right now, so you can't really hover over the titles. The only other way this could work is if the titles would scroll constantly, and I don't think this would work...

But alls episodes should have a context menu attached to them, so you can long press on them to see the whole title.
