### ISSUE TITLE
[Bug] Displaying books in Series

### ISSUE THREAD

**Issue by noneme** [rasmuslos/ShelfPlayer#59]
fFirst and most importantly: friend, CONGRATULATIONS on publishing the application!! you did it! Well done!! 

Lost by application... if the filter “show only unfinished books” is enabled in the library, then in the “Series” section, series in which all books have been read display an empty folder. It would be more logical not to display such a series at all in accordance with the filter.
![image](https://github.com/rasmuslos/ShelfPlayer/assets/5063522/a202690c-dbde-4f26-b651-f08ce0b1018b)

**Comment by rasmuslos** [comment]
Thanks!

Either that but it think it would be better to show all books when this happens
