### ISSUE TITLE
[Feature Request] Add Author Page and Settings page

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#6]
Is it possible we can get the Author page view similar to ABS app? Probably be best to put it in the Library sorting option or a new tab.

Also the app should have a settings page to be able to sign out or sign into another server and other features of the app should be put in there such as light/dark/follow system theme settings
![image](https://github.com/rasmuslos/ShelfPlayer/assets/4202657/90848698-d6eb-4b0b-be4b-b0cd7e06aa4f)

**Comment by gh0sti** [comment]
It's a clean app and I am looking forward to trying to use this over stock ABS from testflight especially since with startup the app loads 5 seconds faster showing book art compared to the ABS app on iOS.

**Comment by rasmuslos** [comment]
Thanks! There is already an account sheet (available when the search tab is selected). Settings are located in the stock settings app, a link is provided on the account sheet

**Comment by rasmuslos** [comment]
An authors view has been added (https://github.com/rasmuslos/ShelfPlayer/commit/ddd5cfc8e5607aacc158d17d3e4eace3c87924fd), it is available in the library tab

**Comment by gh0sti** [comment]
> An authors view has been added (https://github.com/rasmuslos/ShelfPlayer/commit/ddd5cfc8e5607aacc158d17d3e4eace3c87924fd), it is available in the library tab

If you are able to pre compile a new ipa soon I can sideload and take a look at the new features. Thanks for listening to feedback.
