### ISSUE TITLE
[Bug] Siri integration not working?

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#60]
With the appstore version I am not sure how to get siri to work with telling her to play a certain book in shelfplayer. Do you have documentation on how to properly ask siri to play a certain book?

**Comment by rasmuslos** [comment]
You should be able to do it by just asking `Hey Siri play XXX`. At first you might have to specify `Hey Siri play XXX using ShelfPlayer`

**Comment by rasmuslos** [comment]
Did you allow Siri to interact with ShelfPlayer?

**Comment by erictbar** [comment]
Siri works for me with by saying ``Play Lingo``. for a book called ``Lingo: Around Europe in Sixty Languages``. The first time I asked ``Play Lingo with ShelfPlayer`` or something like that. Also I was asked when the app opened if I wanted to enable Siri support. Check your ``Siri & Search`` settings if you don't remember accepting this.

That being said, it does not work with Podcasts for me, which I use much more often than Audiobooks.

**Comment by rasmuslos** [comment]
> Siri works for me with by saying `Play Lingo`. for a book called `Lingo: Around Europe in Sixty Languages`. The first time I asked `Play Lingo with ShelfPlayer` or something like that. Also I was asked when the app opened if I wanted to enable Siri support. Check your `Siri & Search` settings if you don't remember accepting this.
> 
> That being said, it does not work with Podcasts for me, which I use much more often than Audiobooks.

Yes, I know... For some reason that is truly beyond me and can, at least for now, be only explained by Siri-podcast support being an afterthought of the apple engineers, podcast do not work. All the required methods are implemented...

**Comment by gh0sti** [comment]
> Did you allow Siri to interact with ShelfPlayer?
> 
> Also try `Hey Siri play the audiobook XXX`

Yes I did allow for Siri integration when I downloaded and installed the app.

**Comment by gh0sti** [comment]
![image](https://github.com/rasmuslos/ShelfPlayer/assets/4202657/14d58d77-b09b-48d1-9100-13f66a392ea0)

**Comment by rasmuslos** [comment]
Try just `Hey Siri play the Hobbit`

**Comment by gh0sti** [comment]
Asked play the hobbit

![image](https://github.com/rasmuslos/ShelfPlayer/assets/4202657/610db17b-5839-4bd0-af2b-41ad01fc4725)

**Comment by rasmuslos** [comment]
Try using for an audiobook `Hey Siri play the audiobook The Hobbit`

**Comment by gh0sti** [comment]
> Try asking for an audiobook `Hey Siri play the audiobook The Hobbit`

I will go ahead and close this it works but depends on how you pronounce a book for siri, who sucks just plain out right on asking her anything, to think that your asking for a shelfplayer book. One other thing is are you able to integrate shelfplayer in spotlight at all?

**Comment by rasmuslos** [comment]
> > Try asking for an audiobook `Hey Siri play the audiobook The Hobbit`
> 
> I will go ahead and close this it works but depends on how you pronounce a book for siri, who sucks just plain out right on asking her anything, to think that your asking for a shelfplayer book. One other thing is are you able to integrate shelfplayer in spotlight at all?

I don't really handle the STT part, I receive a query from Siri and then look for a matching item in the offline database and them query the ABS server. I am allegedly able to provide some author vocabulary to Siri, but if I do the app just crashes...

A spotlight integration is possible, and it is already implemented partially in AmpFin, but is is very low priority (for example programmatic routing has to get implemented first, something that is quite annoying).
