### ISSUE TITLE
Feature Request: Show download Progress

### ISSUE THREAD

**Issue by jerry00020001** [rasmuslos/ShelfPlayer#62]
Been waiting for this app!! Got it from the AppStore but would it be possible to show download progress?
![IMG_1055](https://github.com/rasmuslos/ShelfPlayer/assets/97918638/c22c6938-0077-468a-9bf5-cb3ec154eeb3)
![IMG_1056](https://github.com/rasmuslos/ShelfPlayer/assets/97918638/7e66a177-bd21-49b6-91e9-f9c9d54971d3)
![IMG_1058](https://github.com/rasmuslos/ShelfPlayer/assets/97918638/40c1b901-98ed-40f9-be67-0e258c2e04ba)

**Comment by gh0sti** [comment]
https://github.com/rasmuslos/ShelfPlayer/issues/28

this was already addressed

**Comment by jerry00020001** [comment]
Damn my bad 😥 didn’t even check

**Comment by rasmuslos** [comment]
But I did not know that a third Hussite book was out, thanks for that!
