### ISSUE TITLE
Request for 1.2 Read Speed

### ISSUE THREAD

**Issue by yamimizu832** [rasmuslos/ShelfPlayer#65]
Is it possible to add 1.2x read speed to the read options. I'm used to using the audiobookshelf beta application and 1.2x read speed is the perfect speed for me personally. 1.25x is just a bit too fast. Thank you for considering the request.

**Comment by rasmuslos** [comment]
You can select custom playback speed adjustments in the settings app (Account -> Settings)

**Comment by yamimizu832** [comment]
Thank you I found the setting and adjusted it from 25% to 10%. I appreciate the fast response and the app you have created :)
