### ISSUE TITLE
(Possible) Bug: Sleeptimer selection menu flickering

### ISSUE THREAD

**Issue by bloodscript** [rasmuslos/ShelfPlayer#66]
ShelfPlayer Version: 2.3.3
iOS Version: 17.4

Expected Behavior: when clicking on the sleeptimer icon a selection menu should pop up which displays all standard and my own sleeptimer durations. This menu should not flicker.

Actual behavior: upon clicking a menu opens up which entries flicker in a regular pattern (see video)

https://github.com/rasmuslos/ShelfPlayer/assets/18524350/a6981e69-eaed-4d76-9531-4fb12a8b59b0

**Comment by rasmuslos** [comment]
I could not reproduce this, do you have any special accessibility, etc. options enabled?

**Comment by bloodscript** [comment]
Hello,
I have no accessibility options activated. I am using an iPhone 12, maybe you could emulate that? I will also try to install it via Xcode maybe it is only valid in the App Store Version (dont know how and why it should be but worth a try)

**Comment by rasmuslos** [comment]
I tried it using an iPhone 12 simulator, but there was no flicker... Maybe try deleting and then installing the app again?

**Comment by bloodscript** [comment]
I deleted the app and installed again - same behavior. I will install it via Xcode so I can see console output.

**Comment by rasmuslos** [comment]
> I deleted the app and installed again - same behavior. I will install it via Xcode so I can see console output.

I doubt that you will get something meaningful out of the logs, but it is worth a try. I would _guess_ that for some reason the view updates constantly. You could try adding a breakpoint or `Self._logChanges()` to `SleepTimerButton.swift` to see what causes these updates (more [here](https://www.avanderlee.com/swiftui/debugging-swiftui-views/)).

**Comment by Tom1206** [comment]
Same issue here, on a iPhone 15 Pro Max on the last App Store version (had the issue for a few builds prior to App Store)

**Comment by rasmuslos** [comment]
> Same issue here, on a iPhone 15 Pro Max on the last App Store version (had the issue for a few builds prior to App Store)

Do you remember the version?

**Comment by rasmuslos** [comment]
@bloodscript were you able to get some debug logs?

**Comment by bloodscript** [comment]
@rasmuslos sorry I was not able. I had to give my MacBook away and can therefore no longer do anything :(

**Comment by rasmuslos** [comment]
The flickering may be caused by the audio player variables updating, maybe I can find the cause
