### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by JBaby9783** [rasmuslos/ShelfPlayer#67]
How do get get this to refresh? I've updated some of the book covers but SP never refreshes to get the new ones.

**Comment by gh0sti** [comment]
> How do get get this to refresh? I've updated some of the book covers but SP never refreshes to get the new ones.

you should be able to do pull down refresh like in safari.

**Comment by JBaby9783** [comment]
I've been doing that. But the covers still aren't updating. I've even forced quit the app too.

**Comment by rasmuslos** [comment]
I think this is related to the Nuke image caching. I will add a `purge cache` button, but it won't be available until the next version. Until then the cache might get invalidated automatically, but I have honestly now idea when this will happen.

But downloads should get the new cover.
