### ISSUE TITLE
Link to GitHub project page is incorrect

### ISSUE THREAD

**Issue by jacobslusser** [rasmuslos/ShelfPlayer#69]
Love the app! Thank you so much for your work.

I noticed that on the **Manage account** screen, the **GitHub** link goes to AmpFin instead of ShelfPlayer.

EDIT:
App Version: 2.3.4 (187)

![IMG_3760](https://github.com/rasmuslos/ShelfPlayer/assets/345183/c330d604-87c0-4302-9c07-640e11a02aac)

**Comment by rasmuslos** [comment]
Thanks! The fix will be released released in the next version
