### ISSUE TITLE
[Feature Request] Download manager and progress bar

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#7]
I would like to see a download manager similar to ABS and a better way to view the progress of downloading a book. Having the spinning wheel doesn't show me how long it's going to take. 
![image](https://github.com/rasmuslos/ShelfPlayer/assets/4202657/af8dae2c-37e8-4eb1-bf6e-8c242586b749)

**Comment by rasmuslos** [comment]
I have added download manager to the account  sheet (https://github.com/rasmuslos/ShelfPlayer/commit/8162ce8e3108ee0e042a9bfcae6a5ec1217bd3e2), but a progress bar is not planned as it would create considerable overhead that is worth the befit
