### ISSUE TITLE
[Feature Request] Setting toggle to lock seek bar in lock screen

### ISSUE THREAD

**Issue by justcallmelarry** [rasmuslos/ShelfPlayer#71]
Currently the seek bar in lock shows the entire book length and is pretty easy to hit by mistake. Which can result in jumping many hours in the book.

Would be great if you had a possibility to lock it, to only be able to seei backwards and forwards with the buttons instead.

Edit: looks like the entire book length is only for certain books, and books with chapters show the chapter length. so it's not as big of an issue on those books, but I would still prefer not to be able to accidentally jump the entire chapter either 😅

**Comment by rasmuslos** [comment]
I added a toggle in the settings app 👍
