### ISSUE TITLE
[Feature Request] Custom headers for server connection

### ISSUE THREAD

**Issue by vicegold** [rasmuslos/ShelfPlayer#72]
I'd like to use ShelfPlayer through a Cloudflare tunnel to access my ABS server on-the-go. For that I need to set 2 custom headers (key/value pairs) to handle authentication. Is that something ShelfPlayer could support?

**Comment by sergpryimachuk** [comment]
+1
I have exactly the same need.

**Comment by gh0sti** [comment]
> +1 I have exactly the same need.

how is that not handled by the URL when entered for the server and username/password? You need to add customer header to get the connection?

**Comment by vicegold** [comment]
> how is that not handled by the URL when entered for the server and username/password? You need to add customer header to get the connection?

Correct, with Cloudflare Tunnels you need an extra layer of authentication so your services aren't exposed to everyone. When opening the ABS UI in the browser you can just can use OTP or Google Auth, but in apps you'll need to use Token auth via custom headers.

**Comment by rasmuslos** [comment]
You can now add custom headers during login or edit them in the account sheet. I am currently working on improving the series handling, when it is finished I will release a new version with this fix.

**Comment by vicegold** [comment]
Wow, that was fast! Thank you so much, really appreciate it!

**Comment by jonathan-catt** [comment]
@vicegold - Sorry to ask you here, but I am trying to make this work on my end but I can't seem to get the Service Token to work with the custom headers from Cloudflare. I have added the CF-Access-Client-Id and CF-Access-Client-Secret as custom headers in Shelf Player, and I have added that service token to a access policy for my ABS application in Cloudflare but I do not see the service token get "hit" in the cloudflare dashboard. Its probably something simple on Cloudflare side but if you have any guidance I would appreciate it.

**Comment by vicegold** [comment]
@jonathan-catt Make sure that you don't just include the token in a regular **Allow** policy. It requires a dedicated Service Auth policy. I stumbled upon this many times as well.

![CleanShot 2024-04-09 at 09 44 01@2x](https://github.com/rasmuslos/ShelfPlayer/assets/3935131/f5502906-df95-4b6c-b566-860955939b65)

**Comment by jonathan-catt** [comment]
Thanks @vicegold 
That was it... didn't even see the service auth action, just figured it was under the Allow action. Knew it was going to be something simple.

**Comment by rasmuslos** [comment]
@vicegold @sergpryimachuk did die you mange to get the actual payback to work? I was thinking about creating a similar setup today and while doing so noticed the all request to the actual audio files are missing the custom HTTP headers. Did you add an exception or does cloudlfare allow media traffic without authentication ?

**Comment by vicegold** [comment]
@rasmuslos It works because Cloudflare is setting a cookie that has the session data. That cookie is still sent when starting the playback, so I'm still authenticated. I've set my session duration to 1 month on Cloudflare and every other API call inside of ShelfPlayer revalidates the session before starting the playback.

**Comment by alx-xlx** [comment]
This need more documentation on how to make it work with cloudflared tunnel, the setup instructions for cloudflared.

I tried and got this

![xnssnWEIjo](https://github.com/user-attachments/assets/00c695d8-b9ca-4c16-b6d0-dd52ba78e1fb)

**Comment by rasmuslos** [comment]
I honestly have no idea how any of this CF stuff works and it’s well beyond the scope of ShelfPlayer to document any of it.
You can ask other users for help, but
I cannot help you.

**Comment by rasmuslos** [comment]
@vicegold this is already fixed in 2.5.0 which will be released soon
