### ISSUE TITLE
listening statistics are not updated

### ISSUE THREAD

**Issue by zichichi** [rasmuslos/ShelfPlayer#73]
if I listen to an audiobook with shelfplayer the listening statistics on audiobookshelf are not updated. The system updates the listening position but not the listening hours on the server page.
These are the logs of a listening session:

<img width="942" alt="image" src="https://github.com/rasmuslos/ShelfPlayer/assets/1170727/3820aa5c-604d-4e40-b5ca-9ff03751773a">

<img width="445" alt="image" src="https://github.com/rasmuslos/ShelfPlayer/assets/1170727/c0da2c20-3da6-475c-adb4-f713b45d1337">

**Comment by rasmuslos** [comment]
This is caused by listening to items while offline. It is (as far as I known) update to update these when using offline listening sessions, but not in an accurate way. I have opened an issue https://github.com/advplyr/audiobookshelf/issues/2795, lets see where this goes.
