### ISSUE TITLE
Unable to FF/REW on AirPods

### ISSUE THREAD

**Issue by KiloNiner** [rasmuslos/ShelfPlayer#74]
First, thanks for making this player — it was pivotal in getting me to adopt audiobookshelf. 

One thing that struck me is the apparent inability to double or triple-tap my AirPods to skip back and forth on the audiobook, mostly needed when I forgot to pay attention if something really cool just happened 😎 

I can still use the controls on the lock screen, but this is way less handy. 

I'm running 17.4.1 on an iPhone 15 Pro, and this gesture usually works when I'm using another audiobook or music player. 

Many thanks for considering my request.

**Comment by KiloNiner** [comment]
This seems to have been resolved in https://github.com/rasmuslos/ShelfPlayer/issues/15#issuecomment-2017706173.

**Comment by rasmuslos** [comment]
Yes, the fix is in app review and should be released soon 👍
