### ISSUE TITLE
Error creating bookmark.

### ISSUE THREAD

**Issue by noneme** [rasmuslos/ShelfPlayer#81]
If the “Show current time in chapter” option is enabled in the settings, the bookmark saves the time for the current chapter, but when you go to a saved chapter, the time is counted from the beginning of the book. In the screenshot, the first two bookmarks are saved with the option enabled, and when you click on them, the book starts at 0:01 or 0:02 of the first chapter. The third tab - with the “Show current war in chapter” option disabled - the timing is correct and the transition is also correct.
![image](https://github.com/rasmuslos/ShelfPlayer/assets/5063522/02713c85-3938-4f8c-81e1-b2bc5bf60405)

**Comment by rasmuslos** [comment]
Fixed 👍 I will upload a new build today, I hope it will go through review fast
