### ISSUE TITLE
Incorrect name in podcast episode filter menu

### ISSUE THREAD

**Issue by noChillGrandma** [rasmuslos/ShelfPlayer#82]
![image](https://github.com/rasmuslos/ShelfPlayer/assets/64256363/30e61ee2-a281-45ca-86fc-eef5ca6815e3)

When trying to filter a podcast episodes by "in progress" or "unlistened" (or however you will call it), I found this duplicate name for the "unlistened" option.

**Comment by rasmuslos** [comment]
Fixed 👍 The German translation is correct, to I never noticed
