### ISSUE TITLE
Colors are lost in interface

### ISSUE THREAD

**Issue by Alarez777** [rasmuslos/ShelfPlayer#83]
In dark mode I feel that the progress bar is lost as it is very similar to the main bar, I think it would be better with more contrast.
<img src="https://github.com/rasmuslos/ShelfPlayer/assets/60858814/85b6074d-2fca-44ec-bb7f-9efa06977213" width="296" height="640">  

Another detail that I have noticed is that the icon that indicates the progress or when the book is finished is lost in light colors perhaps it would be better to remove the transparency.
<img src="https://github.com/rasmuslos/ShelfPlayer/assets/60858814/29a19937-7739-4356-be3e-f1a0643eb859" width="296" height="640">  
And finally a suggestion is for the screen where the information dle book and shows all the chapters would be nice something that would indicate that chaptiulos already listened and the progress of the current chapter for example in the attached screenshot would go in 010 but there is something to indicate it.
     
<img src="https://github.com/rasmuslos/ShelfPlayer/assets/60858814/e45a9c20-fd9e-4fbb-8146-45adbd4ba4c2" width="296" height="640">

**Comment by rasmuslos** [comment]
I updated the progress indicators, but have not yet come up with something better for the chapter list.

**Comment by rasmuslos** [comment]
I will close this in favor of #88
