### ISSUE TITLE
Shelfplayer Library isn't pulling new info from ABS

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#85]
Looking at book artwork that I've updated on ABS and other info Shelf player isn't pulling new data. I'm using 2.4 latest iOS version and 2.9.0 docker server

![image](https://github.com/rasmuslos/ShelfPlayer/assets/4202657/d5e0aad2-f800-402f-8c28-910252d9123d)

![image](https://github.com/rasmuslos/ShelfPlayer/assets/4202657/5f6ece04-b4ca-4324-8c81-fd391ea470a9)

**Comment by gh0sti** [comment]
I wonder if it has to do with caching book covers, but doing a pull down to refresh I would think should pull new data to replace the current cache.

**Comment by rasmuslos** [comment]
You have to click the clear cache button in the account sheet to purge the image cache.

**Comment by gh0sti** [comment]
> You have to click the clear cache button in the account sheet to purge the image cache.

So when I think of progress I understand it as how much you have read/listen in the book. I was able to clear the cache just didn't realize progress was for the image cache. I'm wondering if that can be reworded?

**Comment by rasmuslos** [comment]
It has a different German translation, so it looked fine to me. I wanted to add a footer anyway, so will will change the name, too.

**Comment by gh0sti** [comment]
> It has a different German translation, so it looked fine to me. I wanted to add a footer anyway, so will will change the name, too.

Hey thanks for that fix I appreciate it. Translating and words are hard I can understand.
