### ISSUE TITLE
App crashes when signing out

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#86]
Doing some troubleshooting in reference to my issue #85, signing out of the server crashes the app. I would suggest looking into the logic of handling that use case going back to the sign in page instead of crashing to springboard. 

Same specs 2.4 iOS App Store and abs 2.9
iOS 17.4.1 iPhone 15 PM.

**Comment by rasmuslos** [comment]
It's not really a bug, the app just kills itself. There may be a more elements way though.
