### ISSUE TITLE
[BUG] Chapters do not load at the first time.

### ISSUE THREAD

**Issue by Alarez777** [rasmuslos/ShelfPlayer#88]
Version App: 2.4.0
Version Server: 2.9.0

Chapters do not load the first time. Steps to follow. 
1. Open the book
2. Select chapters
3. You have to go back to the previous screen
4.  Open the same book
5. Select chapters

Video:
https://github.com/rasmuslos/ShelfPlayer/assets/60858814/067332c8-5b3c-45bc-9907-c1647f07e545

**Comment by rasmuslos** [comment]
This is really weird because the expanding _thing_ is a system component, so I would expect it to work reliably... But I wanted do redesign this section anyway.

**Comment by JoshStark** [comment]
Just a +1 from me that this also happens for me as well. Not a huge issue, but hopefully if you rework this area it will get fixed!

**Comment by rasmuslos** [comment]
Do you have an idea how the chapter might be presented?

**Comment by JoshStark** [comment]
Perhaps a new view opens when you tap on “Chapters”, rather than an expandable list on the same view. On the chapter view, it would be nice to be able to tap on a chapter to play from that point as well.

**Comment by Alarez777** [comment]
> Do you have an idea how the chapter might be presented?

I like it as it is, I think it only needs an indicator to know which has already been seen and which is in progress. I can think of 2 options, an indicator similar to the one in the books where you put a check in those that have already been completed and in those that have not, a circle that indicates the progress. Or the other alternative that occurs to me is to apply a color change for example a gray color and that indicates the progress and thus you would see which ones are completed and in those that are not you would see how much is missing.

**Comment by JoshStark** [comment]
Happy to confirm this issue appears to have been resolved in the latest release 👍
