### ISSUE TITLE
[Feature Request] App Settings Additions

### ISSUE THREAD

**Issue by JoshStark** [rasmuslos/ShelfPlayer#89]
Firstly, love the app; the look and feel are excellent. Nice job!

I appreciate you're still relatively early in development but it would be good to have a few extra bits in the app setting section to cover things like:

- Choice of app font (serif vs. sans-serif for example)
- Accent colour choice (yellow is lovely, but a little hard to see on a white background)

I'm a life-long Prologue user, but this looks like a very viable alternative as I'm considering moving permanently to Audiobookshelf.

**Comment by rasmuslos** [comment]
Thanks!

What do you mean by changing the font? If you are in an audiobook library it's serif, otherwise it's sans-serif. What would you change?

**Comment by JoshStark** [comment]
The book titles and page titles. Personally I prefer them to be sans-serif, but it’s not a hugely important thing for me. It’s a configurable setting in Prologue which I’ve become used to. 

I think being able to choose the accent colour to something other than yellow is a bit more important to me because I use the light theme on my phone and iPad, and yellow is really hard to read on a white background.

**Comment by justcallmelarry** [comment]
Adding a +1 for rather having sans-serif than serif 😅 but it's also not a huge deal

**Comment by JoshStark** [comment]
Thank you for the new tint options! Would it be at all possible to have "Black" as an option as well? I know it's quite boring, sorry. I really appreciate the speed at which you are implementing these changes, so please don't think I'm ungrateful!

**Comment by JoshStark** [comment]
Would it also be possible for the "Enable serif font" option to also apply to the view titles, e.g. "Search", "Listen Now" etc?

**Comment by rasmuslos** [comment]
> Would it also be possible for the "Enable serif font" option to also apply to the view titles, e.g. "Search", "Listen Now" etc? It also looks like it hasn't applied to the book title on the active media player.

Restart the app

**Comment by JoshStark** [comment]
I’m an idiot. Thanks!

**Comment by rasmuslos** [comment]
The font of the titles is changed using some UIKit tomfoolery and it's even harder to change on the fly, so restarting (or switching to a podcast library and than back) is the only way to update it...
