### ISSUE TITLE
[Feature Request] Add toggle to disable discover

### ISSUE THREAD

**Issue by gh0sti** [rasmuslos/ShelfPlayer#9]
I believe some users like me would want the ability to disable discover option. 

![image](https://github.com/rasmuslos/ShelfPlayer/assets/4202657/2bdd70a8-8a8b-48c2-8e0f-b5778d289ca9)
![image](https://github.com/rasmuslos/ShelfPlayer/assets/4202657/dc456723-85ed-4dab-bb98-b6e380c76688)

**Comment by rasmuslos** [comment]
Added in https://github.com/rasmuslos/ShelfPlayer/commit/c99056af432dc0a920d8c07d0d9a7a8361a127f2
