### ISSUE TITLE
[Feature Request] Playback History Tracking

### ISSUE THREAD

**Issue by JoshStark** [rasmuslos/ShelfPlayer#90]
Would it be possible for ShelfPlayer to keep track of playback history per audiobook? This would then allow for a timeline to be generated so I can see when I’ve listened to portions of a book, and for how long (start/end timestamps etc). 

I’ve found this to be useful on occasion when losing my place. I can refer back to the history and skip back to a specific timestamp. 

Something similar to how Prologue does it. As far as I know this kind of tracking isn’t supported natively in ABS or Plex (which Prologue uses) so I guess it’d need to be stored locally. 

This is what Prologue looks like:

![IMG_3558](https://github.com/rasmuslos/ShelfPlayer/assets/4211747/f7d41bfc-6f56-4f33-9a2e-a1b01e538ce5)

**Comment by rasmuslos** [comment]
It would be possible to implement this with ABS listening session (your stats), but they only include start/stop, not play/pause. Do you think this would suffice or is there something important about play/pause?

**Comment by JoshStark** [comment]
I think start/stop is probably close enough. I would expect if I pause long enough it would likely be classed as an end to that session anyway. I suspect the play/pause icons are used in the same way in Prologue because there isn’t really a way to “stop” playback other than pausing and closing the app, which is the same thing as in ABS/SP.

**Comment by rasmuslos** [comment]
https://github.com/advplyr/audiobookshelf/pull/2920 is a prerequisite for this
