### ISSUE TITLE
[Feature Request] Prefer local progress

### ISSUE THREAD

**Issue by windoze95** [rasmuslos/ShelfPlayer#92]
I run ABS on a home server, isolated from the internet. If Shelfplayer closes and I reopen it on my network, the progress syncs back to the position on the server. What are your thoughts on preferring the progress position on the app if it is further along than what ABS reports, then updating the ABS progress to match?

**Comment by rasmuslos** [comment]
My ABS instance of also only available inside my local network, so tried to make ShelfPlayer work as good ad possible while offline. I never had this issue before, did you listen to the same item before syncing? ShelfPlayer will use the newer media progress for updates.

**Comment by windoze95** [comment]
The steps below reproduce that behavior for me.
Open ShelfPlayer
Disconnect from network
Play a few minutes of a book
Close ShelfPlayer
Connect to network
Reopen ShelfPlayer

**Comment by rasmuslos** [comment]
This should push your local listening progress to the server. What happens instead?

**Comment by rasmuslos** [comment]
I will close this due to inactivity. Feel free to comment on this again and I will reopen this issue.
