### ISSUE TITLE
[Feature Request] Default playback speed

### ISSUE THREAD

**Issue by 21y4d** [rasmuslos/ShelfPlayer#94]
I've been using the app for a few days, and it works well with Audiobookshelf.

I noticed a few key features missing, so the following would be nice to have:

1. Ability to set the default playback speed "currently need to set the speed every time"

2. Show the real remaining time based on the playback speed "e.g. on 2x speed it would be half the time"

3. Show the total remaining time in the audiobook "all chapters, also based on playback speed"

4. Allow custom playback speeds, like 2.5x and 3x

Thanks for your efforts

**Comment by rasmuslos** [comment]
2. Is already happening 
3. Is visible at the top when you open the chapters / bookmarks sheet and also already implemented

**Comment by 21y4d** [comment]
Nice, I saw both. 

Is the time remaining shown anywhere else other than when the player is minimised? Like in the scroll bar. Probably also show the time remaining in the book "or overall progress" in the player as well, so listeners would know how much is left in the book.

**Comment by 21y4d** [comment]
My request is a default speed for everything, but it would also be great if it can remember the last selected speed for a specific audio book

**Comment by JoshStark** [comment]
Remembering playback speed for a book would be really useful as I have a few books with a narrator who speaks very slowly, so often have them set to 1.2x.

**Comment by iamhenry** [comment]
def agree on both requested features here

books that require a lot of new knowledge and require mental processing I usually play at a lower speed like 1.5x, but books that don't are usually at 1.9x
