### ISSUE TITLE
[Feature Request]Playback Queue for podcasts

### ISSUE THREAD

**Issue by zhimiaoli** [rasmuslos/ShelfPlayer#95]
## Current Behavior
for podcasts in Audiobookshelf, shelfplayer now can only play one eposide at a time, After the current episode finishes playing. user have to manually select another one.

## Desired Behavior

- Ability to automatically and manually add eposide to playback queue, 
- Ability to arrange order in playback queue.

**Comment by zhimiaoli** [comment]
> It seems like the app didn't crash, but the now playing view was not properly dismissed, which blocked interactions.

the crash problem is that I don't have the lastest Xcode,and I built it to run in iOS 17.2,I hardly use Xcode before.

**Comment by rasmuslos** [comment]
The app targets 17.4 because some SwiftUI things don't work as expected on lower versions. But if you have never used Xcode before I would recommend sticking to the pre build binaries.

**Comment by zhimiaoli** [comment]
Apple only allow EU iPhone users to sideload, I am using the app store version in my iPhone.
the App crashes in my xcode simulator so I didn't review the translations.

**Comment by rasmuslos** [comment]
Did you follow [these instructions](https://github.com/rasmuslos/ShelfPlayer#sideload) did you remove the `ENABLE_ALL_FEATURES` flag (step 4)?
