### ISSUE TITLE
[Feature Request] Solid circle colour on book progress corner

### ISSUE THREAD

**Issue by JoshStark** [rasmuslos/ShelfPlayer#97]
Could the progress circle be a solid contrast colour instead of a see-through to the audiobook cover? Some audiobooks covers don’t work well with this scheme and can make it harder to see the wheel progress. 

For example, the contrast isn’t very good for this book:

![image](https://github.com/rasmuslos/ShelfPlayer/assets/4211747/ec74ab06-7dba-4aa2-b1d6-c941f12c480a)

Compared to a contrast colour (e.g. white for darker tints):

![image](https://github.com/rasmuslos/ShelfPlayer/assets/4211747/463c967f-8671-4c5b-8dc0-9a1ffb98a552)

If possible, lighter tints may need a black wheel to keep contrast. 

The same would apply for the “completed” check as well I think. 

I appreciate this is ultimately a design choice which is up to you, however.

**Comment by gh0sti** [comment]
plus 1 on this
