### ISSUE TITLE
[Bug] Series view inconsistent spacing

### ISSUE THREAD

**Issue by JoshStark** [rasmuslos/ShelfPlayer#99]
I seem to get random occasional spacing issues on the Series list page. There doesn't appear to be a pattern to it, but some grid rows end up with huge margins on them. 

Scrolling can skip a little bit as well which seems to affect it too. 

![image](https://github.com/rasmuslos/ShelfPlayer/assets/4211747/4834eabc-4e25-4ad0-874b-49312f40fcc8)

**Comment by gh0sti** [comment]
It's been like this since the app was sideloadable. I don't think rasmuslos has a way to fix it at this time.

**Comment by JoshStark** [comment]
Yeah, to be fair this is very much at the bottom of my list of things I'd consider to be addressed. It's not really bothering me, but figured I'd raise it so it's known.

**Comment by rasmuslos** [comment]
The only cause I can think of is the series "cover" (composed of multiple images), because its the only real difference to something like the audiobooks grid which does not appear to have this bug.
